.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH vdssh 1 "24 August 2008" VDSF "User Commands"
.SH NAME
vdssh \- starts a pseudo-shell to access VDSF data
.SH SYNOPSIS
.SS "GETTING (MINIMAL) HELP:"
\*(T<\fBvdssh \-h|\-\-help|\-?\fR\*(T>
.SS "RUNNING NORMALLY:"
\*(T<\fBvdssh \-a|\-\-address\fR\*(T> \fIquasar_address \fR
.SH DESCRIPTION
vdssh is a pseudo-shell allowing access to the data in the VDS 
(shared-memory used by the VDSF software).
.PP
This program supports a very limited number of standard Bourne shell commands 
(and a few equivalent DOS commands). See the section 
\fBCOMMANDS\fR
for a list of supported commands (and syntax).
.SH OPTIONS
.TP 
\*(T<\fB\-a\fR\*(T>, \*(T<\fB\-\-address\fR\*(T> \fIquasar_address\fR
The TCP port for the VDSF watchdog (the program quasar).
.TP 
\*(T<\fB\-h\fR\*(T>, \*(T<\fB\-?\fR\*(T>, \*(T<\fB\-\-help\fR\*(T>
Minimal help including a list of supported commands.
.SH COMMANDS
The syntax of the commands is simpler than the equivalent Bourne shell 
commands - most commands take no options.
.PP
Names of objects (data containers) can be either absolute (starting with /)
or relative to the current folder (see the \fBcd
\fRcommand for an explanation on how to change the current folder).
.TP 
\fBcat\fR \fIobject_name\fR
Display the content of the object named object_name.

\fBWarning: \fRcat will print the output as strings.
.TP 
\fBcd\fR \fI[folder_name]\fR
Without a name, change the current folder to "/". Change the current 
folder to folder_name.
.TP 
\fBcp\fR \fIsource_name dest_name\fR
Copy the source_name object to the dest_name object.

\fBWarning: \fR
dest_name is not overwritten if it already exists.
.TP 
\fBdel/rm\fR \fIobject_name\fR
Delete the data container named object_name.
.TP 
\fBdir/ls\fR \fI[folder_name]\fR
Without a name, list the objects of the current folder. List the 
objects of the folder folder_name.
.TP 
\fBexit/quit\fR
Exit the program.
.TP 
\fBfree\fR
Display the amount of used/free memory (main allocator).
.TP 
\fBhelp/man\fR
Display the current list of commands.
.TP 
\fBmkdir\fR \fIfolder_name\fR
Create a new folder.
.TP 
\fBpwd\fR
Display the current folder.
.TP 
\fBrmdir\fR \fIfolder_name\fR
Delete the folder named folder_name.
.TP 
\fBstat\fR \fIobject_name\fR
Show the status of the object named \fIobject_name\fR.
.TP 
\fBtouch -h|-q\fR \fIobject_name\fR
Create a new object named object_name of the specified type:

-h or --hashmap: a hash map
.br
-q or --queue: a FIFO queue
.SH "REPORTING BUGS"
Report bugs to <dprevost@users.sourceforge.net>.
.SH COPYRIGHT
Copyright \(^A\(co 2008 Daniel Pr\('evost.
