# Copyright (C) 2007-2008 Daniel Prevost <dprevost@users.sourceforge.net>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

check_PROGRAMS =                                \
                 .\Release\CloseNullContext.exe \
                 .\Release\CloseNullProcess.exe \
                 .\Release\ClosePass.exe        \
                 .\Release\FiniNullProcess.exe  \
                 .\Release\FiniPass.exe         \
                 .\Release\InitNullAddr.exe     \
                 .\Release\InitNullProcess.exe  \
                 .\Release\InitPass.exe         \
                 .\Release\InitWrongAddr.exe    \
                 .\Release\OpenNullContext.exe  \
                 .\Release\OpenNullFilename.exe \
                 .\Release\OpenNullProcess.exe  \
                 .\Release\OpenPass.exe         

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

