# Copyright (C) 2007 Daniel Prevost <dprevost@users.sourceforge.net>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

CLEANFILES = *~ 

check_PROGRAMS =                                    \
                 .\Release\FiniNullBitmap.exe       \
                 .\Release\FiniPass.exe             \
                 .\Release\GetLengthPass.exe        \
                 .\Release\GetLengthPowerOfTwo7.exe \
                 .\Release\GetLengthPowerOfTwo9.exe \
                 .\Release\GetLengthZeroLength.exe  \
                 .\Release\GetLengthZeroGranu.exe   \
                 .\Release\InitNullBitmap.exe       \
                 .\Release\InitNullOffset.exe       \
                 .\Release\InitPass.exe             \
                 .\Release\InitPowerOfTwo7.exe      \
                 .\Release\InitPowerOfTwo9.exe      \
                 .\Release\InitZeroGranu.exe        \
                 .\Release\InitZeroLength.exe       \
                 .\Release\IsFreeNullBitmap.exe     \
                 .\Release\IsFreeNullOffset.exe     \
                 .\Release\IsFreePass.exe           \
                 .\Release\SetAllocNullBitmap.exe   \
                 .\Release\SetAllocNullOffset.exe   \
                 .\Release\SetAllocPass.exe         \
                 .\Release\SetAllocZeroLength.exe   \
                 .\Release\SetFreeNullBitmap.exe    \
                 .\Release\SetFreeNullOffset.exe    \
                 .\Release\SetFreePass.exe          

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)
#

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

