# Copyright (C) 2006-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

all: 

check_PROGRAMS =                             \
        $(DIR_RELEASE)\AddNullApiSession.exe   \
        $(DIR_RELEASE)\AddNullContext.exe      \
        $(DIR_RELEASE)\AddNullProcess.exe      \
        $(DIR_RELEASE)\AddNullSession.exe      \
        $(DIR_RELEASE)\AddPass.exe             \
        $(DIR_RELEASE)\FiniNullContext.exe     \
        $(DIR_RELEASE)\FiniNullProcess.exe     \
        $(DIR_RELEASE)\FiniPass.exe            \
        $(DIR_RELEASE)\GetFirstNullContext.exe \
        $(DIR_RELEASE)\GetFirstNullProcess.exe \
        $(DIR_RELEASE)\GetFirstNullSession.exe \
        $(DIR_RELEASE)\GetFirstPass.exe        \
        $(DIR_RELEASE)\GetNextNullContext.exe  \
        $(DIR_RELEASE)\GetNextNullCurrent.exe  \
        $(DIR_RELEASE)\GetNextNullNext.exe     \
        $(DIR_RELEASE)\GetNextNullProcess.exe  \
        $(DIR_RELEASE)\GetNextPass.exe         \
        $(DIR_RELEASE)\InitNullContext.exe     \
        $(DIR_RELEASE)\InitNullProcess.exe     \
        $(DIR_RELEASE)\InitPass.exe            \
        $(DIR_RELEASE)\InitZeroPid.exe         \
        $(DIR_RELEASE)\RemoveNullContext.exe   \
        $(DIR_RELEASE)\RemoveNullProcess.exe   \
        $(DIR_RELEASE)\RemoveNullSession.exe   \
        $(DIR_RELEASE)\RemovePass.exe          

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q $(CLEANFILES)

