###########################################################################
#
# Copyright (C) 2007-2008 Daniel Prevost <dprevost@users.sourceforge.net>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
###########################################################################

VBS_VERBOSE=

CLEANFILES = *~  vc60.pdb

W32_SYS_LIBS=kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib
LDD_FLAGS = $(W32_SYS_LIBS)     vdsfcpp.lib vdsfAPI.lib vdsfEngine.lib vdsfCommon.lib /nologo /IGNORE:4089 /subsystem:console /machine:I386 /libpath:"../Release" 
LDD_FLAGS_DEBUG=$(W32_SYS_LIBS) vdsfcpp.lib vdsfAPI.lib vdsfEngine.lib vdsfCommon.lib /nologo /IGNORE:4089 /subsystem:console /machine:I386 /libpath:"../Debug" 

OUTDIR=.\Release
INTDIR=.\Release
OUTDIR_DEBUG=.\Debug
INTDIR_DEBUG=.\Debug

CFLAGS_DEBUG=   /nologo /MDd /W3 /Zi /I ".." /I "../include" /D "WIN32" /D "_DEBUG" /D "_CONSOLE" /D "_MBCS" /Fo"$(INTDIR_DEBUG)\\" 
CFLAGS_RELEASE= /nologo /MD  /W3 /O2 /I ".." /I "../include" /D "WIN32" /D "NDEBUG" /D "_CONSOLE" /D "_MBCS" /Fo"$(INTDIR)\\" 

.c{$(OUTDIR)}.exe:
	$(CPP) $(CFLAGS_RELEASE) $< /link $(LDD_FLAGS) /out:"$@"

.cpp{$(OUTDIR)}.exe:
	$(CPP) $(CFLAGS_RELEASE) $< /link $(LDD_FLAGS) /out:"$@"

.c{$(OUTDIR_DEBUG)}.exe:
	$(CPP) $(CFLAGS_DEBUG) $< /link $(LDD_FLAGS_DEBUG) /out:"$@"

"$(OUTDIR)" :
	if not exist "$(OUTDIR)/" mkdir "$(OUTDIR)"

"$(OUTDIR_DEBUG)" :
	if not exist "$(OUTDIR_DEBUG)/" mkdir "$(OUTDIR_DEBUG)"

###########################################################################

all: 

check_PROGRAMS =      \
   .\Release\TransactionHashMap.exe \
   .\Release\TransactionQueue.exe   \
   .\Release\InjectErrorsVDS.exe    \
   .\Release\OutOfMemory.exe        

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)
#

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

#InjectErrorsVDS_SOURCES    = InjectErrorsVDS.cpp
#OutOfMemory_SOURCES        = OutOfMemory.cpp
#TransactionHashMap_SOURCES = TransactionHashMap.c
#TransactionQueue_SOURCES   = TransactionQueue.c

#LDADD = $(top_builddir)/src/API/libvdsf.la      \
#        $(top_builddir)/src/Engine/libEngine.la \
#        $(top_builddir)/src/Common/libCommon.la

#InjectErrorsVDS_LDADD = $(top_builddir)/src/C++/libvdsfcpp.la 
#OutOfMemory_LDADD = $(top_builddir)/src/C++/libvdsfcpp.la 

