# Copyright (C) 2007-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include .\Makefile.inc.Win32.2005

#
# Override the values in Makefile.inc.Win32
#
LDD_FLAGS = $(W32_SYS_LIBS) photonCommon.lib /nologo /subsystem:console /machine:I386 /libpath:"../../Release2005" 
LDD_FLAGS_DEBUG=$(W32_SYS_LIBS) photonCommon.lib /nologo /subsystem:console /machine:I386 /libpath:"../../Debug2005" 
CFLAGS_DEBUG=   /nologo /MDd /W4     /I ".." /I "../.." /I "../../.." /I "../../Tests" /D "WIN32" /D "_DEBUG" /D "_CONSOLE" /D "_MBCS" /Fo"$(DIR_DEBUG)\\" 
CFLAGS_RELEASE= /nologo /MD  /W4 /O2 /I ".." /I "../.." /I "../../.." /I "../../Tests" /D "WIN32" /D "NDEBUG" /D "_CONSOLE" /D "_MBCS" /Fo"$(DIR_RELEASE)\\" 
DLL_RELEASE = ..\..\Release2005
DLL_DEBUG   = ..\..\Debug2005

all: 

CLEANFILES = *~ TestsCommon.ncb

check_PROGRAMS =                         \
        $(DIR_RELEASE)\TimerTest.exe     

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
   cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)
	cd DirAccess   && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Error       && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd MemFile     && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Options     && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd ProcessLock && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd ThreadLock  && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)
	cd DirAccess   && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Error       && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd MemFile     && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Options     && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd ProcessLock && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd ThreadLock  && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..

clean: 
	cd DirAccess   && nmake -f Makefile.win32 clean && cd ..
	cd Error       && nmake -f Makefile.win32 clean && cd ..
	cd MemFile     && nmake -f Makefile.win32 clean && cd ..
	cd Options     && nmake -f Makefile.win32 clean && cd ..
	cd ProcessLock && nmake -f Makefile.win32 clean && cd ..
	cd ThreadLock  && nmake -f Makefile.win32 clean && cd ..
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q $(CLEANFILES)

