#! /usr/bin/env python
# encoding: utf-8
# :mode=python:  - For jedit

# Copyright (C) 2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

def build(bld):
   print ' building in Tests'
   
   obj = bld.new_task_gen(
      features     = 'cc cprogram',
      source       = 'TimerTest.c',
      target       = 'TimerTest',
      includes     = '../..',
      install_path = None,
      lib          = bld.env['CMOCKERY'],
      uselib_local = 'Common') 
   if bld.env['CMOCKERY'] and bld.env['MORE_TESTS']:
      obj.unit_test = 1

   bld.add_subdirs([
        'DirAccess',
        'Error',
        'MemFile',
        'Options',
        'ProcessLock',
        'ThreadLock'])

