#! /usr/bin/env python
# encoding: utf-8
# :mode=python:  - For jedit

# Copyright (C) 2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

test_list = ['DirAccess.c',
               'ErrorHandler.c',
               'MemoryFile.c',
               'Options.c',
               'ProcessLock.c',
               'ThreadLock.c',
               'Timer.c']


#   bld.add_subdirs(['Common'])
def check(ctx):
#   ctx.recurse('Tests')
   print 'ok check'
   print dir(ctx)
'''
bld.new_task_gen(
      features       = 'cc cprogram',
      source         = 'nanosleepTest.c',
      target         = 'nanosleepTest',
      includes       = '../..',
      uselib_local   = 'Common') 
'''
#nanosleepTest.c
#TimerTest_SOURCES     = TimerTest.c
