/*
 * Copyright (C) 2008 Daniel Prevost <dprevost@users.sourceforge.net>
 *
 * This file is part of vdsf (Virtual Data Space Framework).
 *
 * This file may be distributed and/or modified under the terms of the
 * GNU General Public License version 2 as published by the Free Software
 * Foundation and appearing in the file COPYING included in the
 * packaging of this library.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 */

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#include "Common/Common.h"
#include <vdsf/vdsCommon.h>

#include <libxml/xmlschemas.h>
#include <libxml/xmlschemastypes.h>

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

void writeHeader( FILE * fp, const char * name ) 
{
   unsigned int i;
   
   fprintf( fp, "%s\n\n",
      "/*\n"
      " * This file was generated by the program vdsxml2c - which\n"
      " * is part of vdsf (the Virtual Data Space Framework).\n"
      " *\n"
      " * Since this file is generated, it has no copyright.\n"
      " * You can incorporate it in your projects as you wish.\n"
      " *\n"
      " * This code is generated in the hope it will be useful, but\n"
      " * WITHOUT ANY WARRANTY; without even the implied warranty of\n"
      " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. \n"
      " */" );
   
   fprintf( fp, "#ifndef " );
   for ( i = 0; i < strlen(name); ++i ) {
      fprintf( fp, "%c", toupper(name[i]) );
   }
   fprintf( fp, "_H\n#define " );
   for ( i = 0; i < strlen(name); ++i ) {
      fprintf( fp, "%c", toupper(name[i]) );
   }
   fprintf( fp, "_H\n\n" );
}

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

void writeTrailer( FILE * fp, const char * name ) 
{
   unsigned int i;
   
   fprintf( fp, "#endif /* " );
   for ( i = 0; i < strlen(name); ++i ) {
      fprintf( fp, "%c", toupper(name[i]) );
   }
   fprintf( fp, "_H */\n\n" );
}

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

int validateName( xmlChar * name )
{
   char * objectName = (char *)name;

   size_t i;
   
   /* The first char is always special - it cannot be '/' */
   if ( ! isalpha( (int) objectName[0] )  ) {
      return -1;
      //VDS_INVALID_OBJECT_NAME;
   }
   
   for ( i = 1; i < strlen(objectName ); ++i ) {
      if ( !( isalnum((int) objectName[i]) || (objectName[i] == '_') ) ) {
         return -1;
      }
   }
   if ( i > VDS_MAX_NAME_LENGTH ) {
      return -1;
      //VDS_OBJECT_NAME_TOO_LONG;
   }
   
   return 0;
}

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */
