# Copyright (C) 2007-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

all: 

check_PROGRAMS =                                 \
        $(DIR_RELEASE)\FiniInvSig.exe                 \
        $(DIR_RELEASE)\FiniNullList.exe               \
        $(DIR_RELEASE)\FiniPass.exe                   \
        $(DIR_RELEASE)\GetFirstInvSig.exe             \
        $(DIR_RELEASE)\GetFirstNullItem.exe           \
        $(DIR_RELEASE)\GetFirstNullList.exe           \
        $(DIR_RELEASE)\GetFirstPass.exe               \
        $(DIR_RELEASE)\GetLastInvSig.exe              \
        $(DIR_RELEASE)\GetLastNullItem.exe            \
        $(DIR_RELEASE)\GetLastNullList.exe            \
        $(DIR_RELEASE)\GetLastPass.exe                \
        $(DIR_RELEASE)\InitNullList.exe               \
        $(DIR_RELEASE)\InitPass.exe                   \
        $(DIR_RELEASE)\IsValidInvSig.exe              \
        $(DIR_RELEASE)\IsValidNullList.exe            \
        $(DIR_RELEASE)\IsValidNullUnknown.exe         \
        $(DIR_RELEASE)\IsValidPass.exe                \
        $(DIR_RELEASE)\PeakFirstInvSig.exe            \
        $(DIR_RELEASE)\PeakFirstNullItem.exe          \
        $(DIR_RELEASE)\PeakFirstNullList.exe          \
        $(DIR_RELEASE)\PeakFirstPass.exe              \
        $(DIR_RELEASE)\PeakLastInvSig.exe             \
        $(DIR_RELEASE)\PeakLastNullItem.exe           \
        $(DIR_RELEASE)\PeakLastNullList.exe           \
        $(DIR_RELEASE)\PeakLastPass.exe               \
        $(DIR_RELEASE)\PeakNextInvSig.exe             \
        $(DIR_RELEASE)\PeakNextNullCurrent.exe        \
        $(DIR_RELEASE)\PeakNextNullCurrNextOffset.exe \
        $(DIR_RELEASE)\PeakNextNullCurrPrevOffset.exe \
        $(DIR_RELEASE)\PeakNextNullList.exe           \
        $(DIR_RELEASE)\PeakNextNullNext.exe           \
        $(DIR_RELEASE)\PeakNextPass.exe               \
        $(DIR_RELEASE)\PeakPreviousInvSig.exe         \
        $(DIR_RELEASE)\PeakPreviousNullCurrent.exe    \
        $(DIR_RELEASE)\PeakPrevNullCurrNextOffset.exe \
        $(DIR_RELEASE)\PeakPrevNullCurrPrevOffset.exe \
        $(DIR_RELEASE)\PeakPreviousNullList.exe       \
        $(DIR_RELEASE)\PeakPreviousNullPrevious.exe   \
        $(DIR_RELEASE)\PeakPreviousPass.exe           \
        $(DIR_RELEASE)\PutFirstInvSig.exe             \
        $(DIR_RELEASE)\PutFirstNullList.exe           \
        $(DIR_RELEASE)\PutFirstNullNewItem.exe        \
        $(DIR_RELEASE)\PutFirstNullNewNext.exe        \
        $(DIR_RELEASE)\PutFirstNullNewPrevious.exe    \
        $(DIR_RELEASE)\PutFirstPass.exe               \
        $(DIR_RELEASE)\PutLastInvSig.exe              \
        $(DIR_RELEASE)\PutLastNullList.exe            \
        $(DIR_RELEASE)\PutLastNullNewItem.exe         \
        $(DIR_RELEASE)\PutLastNullNewNext.exe         \
        $(DIR_RELEASE)\PutLastNullNewPrevious.exe     \
        $(DIR_RELEASE)\PutLastPass.exe                \
        $(DIR_RELEASE)\RemoveInvSig.exe               \
        $(DIR_RELEASE)\RemoveAbsent.exe               \
        $(DIR_RELEASE)\RemoveNullItem.exe             \
        $(DIR_RELEASE)\RemoveNullNextOffset.exe       \
        $(DIR_RELEASE)\RemoveNullPrevOffset.exe       \
        $(DIR_RELEASE)\RemoveNullList.exe             \
        $(DIR_RELEASE)\RemovePass.exe                 \
        $(DIR_RELEASE)\RemoveWrongItem.exe            \
        $(DIR_RELEASE)\ReplaceInvSig.exe              \
        $(DIR_RELEASE)\ReplaceNullList.exe            \
        $(DIR_RELEASE)\ReplaceNullNew.exe             \
        $(DIR_RELEASE)\ReplaceNullNewNext.exe         \
        $(DIR_RELEASE)\ReplaceNullNewPrevious.exe     \
        $(DIR_RELEASE)\ReplaceNullOld.exe             \
        $(DIR_RELEASE)\ReplacePass.exe                \
        $(DIR_RELEASE)\ResetInvSig.exe                \
        $(DIR_RELEASE)\ResetNullList.exe              \
        $(DIR_RELEASE)\ResetPass.exe                  \
        $(DIR_RELEASE)\TestSmall.exe                  \
        $(DIR_RELEASE)\TestBig.exe                    

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q $(CLEANFILES)

