# Copyright (C) 2006-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

check_PROGRAMS =                               \
        .\Release\CommitAddNullOffset.exe      \
        .\Release\CommitAddNullQueue.exe       \
        .\Release\CommitAddPass.exe            \
        .\Release\CommitRemoveNullContext.exe  \
        .\Release\CommitRemoveNullOffset.exe   \
        .\Release\CommitRemoveNullQueue.exe    \
        .\Release\CommitRemovePass.exe         \
        .\Release\FiniNullContext.exe          \
        .\Release\FiniNullQueue.exe            \
        .\Release\FiniPass.exe                 \
        .\Release\GetNullContext.exe           \
        .\Release\GetNullQueue.exe             \
        .\Release\GetNullIterator.exe          \
        .\Release\GetPass.exe                  \
        .\Release\GetWrongFlag.exe             \
        .\Release\GetWrongLength.exe           \
        .\Release\InitNullContext.exe          \
        .\Release\InitNullDataDef.exe          \
        .\Release\InitNullDefinition.exe       \
        .\Release\InitNullHashItem.exe         \
        .\Release\InitNullQueue.exe            \
        .\Release\InitNullName.exe             \
        .\Release\InitNullParent.exe           \
        .\Release\InitNullStatus.exe           \
        .\Release\InitPass.exe                 \
        .\Release\InitZeroBlocks.exe           \
        .\Release\InitZeroDataDefLength.exe    \
        .\Release\InitZeroLength.exe           \
        .\Release\InsertNowNullContext.exe     \
        .\Release\InsertNowNullItem.exe        \
        .\Release\InsertNowNullQueue.exe       \
        .\Release\InsertNowPass.exe            \
        .\Release\InsertNowWrongFlag.exe       \
        .\Release\InsertNowZeroLengthItem.exe  \
        .\Release\InsertNullContext.exe        \
        .\Release\InsertNullQueue.exe          \
        .\Release\InsertNullItem.exe           \
        .\Release\InsertPass.exe               \
        .\Release\InsertWrongFlag.exe          \
        .\Release\InsertZeroLengthItem.exe     \
        .\Release\ReleaseNullContext.exe       \
        .\Release\ReleaseNullItem.exe          \
        .\Release\ReleaseNullQueue.exe         \
        .\Release\ReleasePass.exe              \
        .\Release\ReleaseNoLockNullContext.exe \
        .\Release\ReleaseNoLockNullItem.exe    \
        .\Release\ReleaseNoLockNullQueue.exe   \
        .\Release\ReleaseNoLockPass.exe        \
        .\Release\RemoveNullContext.exe        \
        .\Release\RemoveNullItem.exe           \
        .\Release\RemoveNullQueue.exe          \
        .\Release\RemovePass.exe               \
        .\Release\RemoveWrongFlag.exe          \
        .\Release\RemoveWrongLength.exe        \
        .\Release\RollbackAddNullContext.exe   \
        .\Release\RollbackAddNullOffset.exe    \
        .\Release\RollbackAddNullQueue.exe     \
        .\Release\RollbackAddPass.exe          \
        .\Release\RollbackRemoveNullOffset.exe \
        .\Release\RollbackRemoveNullQueue.exe  \
        .\Release\RollbackRemovePass.exe       \
        .\Release\StatusNullQueue.exe          \
        .\Release\StatusNullStatus.exe         \
        .\Release\StatusPass.exe               

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

