# Copyright (C) 2006-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

all: 

check_PROGRAMS =                               \
        $(DIR_RELEASE)\CommitAddNullOffset.exe      \
        $(DIR_RELEASE)\CommitAddNullQueue.exe       \
        $(DIR_RELEASE)\CommitAddPass.exe            \
        $(DIR_RELEASE)\CommitRemoveNullContext.exe  \
        $(DIR_RELEASE)\CommitRemoveNullOffset.exe   \
        $(DIR_RELEASE)\CommitRemoveNullQueue.exe    \
        $(DIR_RELEASE)\CommitRemovePass.exe         \
        $(DIR_RELEASE)\FiniNullContext.exe          \
        $(DIR_RELEASE)\FiniNullQueue.exe            \
        $(DIR_RELEASE)\FiniPass.exe                 \
        $(DIR_RELEASE)\GetNullContext.exe           \
        $(DIR_RELEASE)\GetNullQueue.exe             \
        $(DIR_RELEASE)\GetNullIterator.exe          \
        $(DIR_RELEASE)\GetPass.exe                  \
        $(DIR_RELEASE)\GetWrongLength.exe           \
        $(DIR_RELEASE)\InitNullContext.exe          \
        $(DIR_RELEASE)\InitNullDataDef.exe          \
        $(DIR_RELEASE)\InitNullDefinition.exe       \
        $(DIR_RELEASE)\InitNullHashItem.exe         \
        $(DIR_RELEASE)\InitNullQueue.exe            \
        $(DIR_RELEASE)\InitNullName.exe             \
        $(DIR_RELEASE)\InitNullParent.exe           \
        $(DIR_RELEASE)\InitNullStatus.exe           \
        $(DIR_RELEASE)\InitPass.exe                 \
        $(DIR_RELEASE)\InitZeroBlocks.exe           \
        $(DIR_RELEASE)\InitZeroLength.exe           \
        $(DIR_RELEASE)\InsertNowNullContext.exe     \
        $(DIR_RELEASE)\InsertNowNullItem.exe        \
        $(DIR_RELEASE)\InsertNowNullQueue.exe       \
        $(DIR_RELEASE)\InsertNowPass.exe            \
        $(DIR_RELEASE)\InsertNowWrongFlag.exe       \
        $(DIR_RELEASE)\InsertNowZeroLengthItem.exe  \
        $(DIR_RELEASE)\InsertNullContext.exe        \
        $(DIR_RELEASE)\InsertNullQueue.exe          \
        $(DIR_RELEASE)\InsertNullItem.exe           \
        $(DIR_RELEASE)\InsertPass.exe               \
        $(DIR_RELEASE)\InsertWrongFlag.exe          \
        $(DIR_RELEASE)\InsertZeroLengthItem.exe     \
        $(DIR_RELEASE)\ReleaseNullContext.exe       \
        $(DIR_RELEASE)\ReleaseNullItem.exe          \
        $(DIR_RELEASE)\ReleaseNullQueue.exe         \
        $(DIR_RELEASE)\ReleasePass.exe              \
        $(DIR_RELEASE)\ReleaseNoLockNullContext.exe \
        $(DIR_RELEASE)\ReleaseNoLockNullItem.exe    \
        $(DIR_RELEASE)\ReleaseNoLockNullQueue.exe   \
        $(DIR_RELEASE)\ReleaseNoLockPass.exe        \
        $(DIR_RELEASE)\RemoveNullContext.exe        \
        $(DIR_RELEASE)\RemoveNullItem.exe           \
        $(DIR_RELEASE)\RemoveNullQueue.exe          \
        $(DIR_RELEASE)\RemovePass.exe               \
        $(DIR_RELEASE)\RemoveWrongFlag.exe          \
        $(DIR_RELEASE)\RemoveWrongLength.exe        \
        $(DIR_RELEASE)\RollbackAddNullContext.exe   \
        $(DIR_RELEASE)\RollbackAddNullOffset.exe    \
        $(DIR_RELEASE)\RollbackAddNullQueue.exe     \
        $(DIR_RELEASE)\RollbackAddPass.exe          \
        $(DIR_RELEASE)\RollbackRemoveNullOffset.exe \
        $(DIR_RELEASE)\RollbackRemoveNullQueue.exe  \
        $(DIR_RELEASE)\RollbackRemovePass.exe       \
        $(DIR_RELEASE)\StatusNullQueue.exe          \
        $(DIR_RELEASE)\StatusNullStatus.exe         \
        $(DIR_RELEASE)\StatusPass.exe               

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q $(CLEANFILES)

