# Copyright (C) 2006-2008 Daniel Prevost <dprevost@users.sourceforge.net>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

check_PROGRAMS =                                       \
                 .\Release\CloseNullContext.exe        \
                 .\Release\CloseNullItem.exe           \
                 .\Release\ClosePass.exe               \
                 .\Release\CreateInvalidNameLength.exe \
                 .\Release\CreateNullContext.exe       \
                 .\Release\CreateNullFolder.exe        \
                 .\Release\CreateNullName.exe          \
                 .\Release\CreatePass.exe              \
                 .\Release\CreateWrongType.exe         \
                 .\Release\DeleteInvalidSig.exe        \
                 .\Release\DeleteNullContext.exe       \
                 .\Release\DeleteNullFolder.exe        \
                 .\Release\DeleteNullName.exe          \
                 .\Release\DeletePass.exe              \
                 .\Release\DeleteWrongObjType.exe      \
                 .\Release\DeleteZeroNameLength.exe    \
                 .\Release\DestroyNullContext.exe      \
                 .\Release\DestroyNullFolder.exe       \
                 .\Release\DestroyNullName.exe         \
                 .\Release\DestroyPass.exe             \
                 .\Release\FiniInvalidSig.exe          \
                 .\Release\FiniNullContext.exe         \
                 .\Release\FiniNullFolder.exe          \
                 .\Release\FiniPass.exe                \
                 .\Release\FiniWrongObjType.exe        \
                 .\Release\GetFirstEmpty.exe           \
                 .\Release\GetFirstNullContext.exe     \
                 .\Release\GetFirstNullFolder.exe      \
                 .\Release\GetFirstNullItem.exe        \
                 .\Release\GetFirstPass.exe            \
                 .\Release\GetFirstWrongObjType.exe    \
                 .\Release\GetInvalidSig.exe           \
                 .\Release\GetNextItemNullHashItem.exe \
                 .\Release\GetNextItemNullOffset.exe   \
                 .\Release\GetNextNullContext.exe      \
                 .\Release\GetNextNullFolder.exe       \
                 .\Release\GetNextNullItem.exe         \
                 .\Release\GetNextPass.exe             \
                 .\Release\GetNextWrongObjType.exe     \
                 .\Release\GetNullContext.exe          \
                 .\Release\GetNullItem.exe             \
                 .\Release\GetNullFolder.exe           \
                 .\Release\GetNullName.exe             \
                 .\Release\GetPass.exe                 \
                 .\Release\GetStatusNullContext.exe    \
                 .\Release\GetStatusNullFolder.exe     \
                 .\Release\GetStatusNullName.exe       \
                 .\Release\GetStatusPass.exe           \
                 .\Release\GetStatusZeroLength.exe     \
                 .\Release\GetWrongObjType.exe         \
                 .\Release\GetZeroNameLength.exe       \
                 .\Release\InitNullContext.exe         \
                 .\Release\InitNullFolder.exe          \
                 .\Release\InitNullKeyOffset.exe       \
                 .\Release\InitNullName.exe            \
                 .\Release\InitNullParentOffset.exe    \
                 .\Release\InitPass.exe                \
                 .\Release\InitZeroBlocks.exe          \
                 .\Release\InitZeroNameLength.exe      \
                 .\Release\InsertInvalidSig.exe        \
                 .\Release\InsertNullContext.exe       \
                 .\Release\InsertNullFolder.exe        \
                 .\Release\InsertNullName.exe          \
                 .\Release\InsertNullOrigName.exe      \
                 .\Release\InsertPass.exe              \
                 .\Release\InsertWrongObjType.exe      \
                 .\Release\InsertZeroBlocks.exe        \
                 .\Release\InsertZeroNameLength.exe    \
                 .\Release\OpenNullContext.exe         \
                 .\Release\OpenNullItem.exe            \
                 .\Release\OpenNullFolder.exe          \
                 .\Release\OpenNullName.exe            \
                 .\Release\OpenPass.exe                \
                 .\Release\ReleaseNullContext.exe      \
                 .\Release\ReleaseNullFolder.exe       \
                 .\Release\ReleaseNullItem.exe         \
                 .\Release\ReleasePass.exe             \
                 .\Release\ReleaseWrongObjType.exe     \
                 .\Release\RemoveNullContext.exe       \
                 .\Release\RemoveNullFolder.exe        \
                 .\Release\RemoveNullName.exe          \
                 .\Release\RemovePass.exe              \
                 .\Release\RemoveWrongObjType.exe      \
                 .\Release\RemoveZeroLength.exe        \
                 .\Release\StatusNullFolder.exe        \
                 .\Release\StatusNullStatus.exe        \
                 .\Release\StatusPass.exe              \
                 .\Release\Tests.exe                   \
                 .\Release\TopStatusNullContext.exe    \
                 .\Release\TopStatusNullFolder.exe     \
                 .\Release\TopStatusNullName.exe       \
                 .\Release\TopStatusNullStatus.exe     \
                 .\Release\TopStatusPass.exe           \
                 .\Release\ValidatePass.exe            

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)
#

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

