# Copyright (C) 2006-2007 Daniel Prevost <dprevost@users.sourceforge.net>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

check_PROGRAMS =                                    \
                 .\Release\DeleteInvalidSig.exe     \
                 .\Release\DeleteNullContext.exe    \
                 .\Release\DeleteNullFolder.exe     \
                 .\Release\DeleteNullName.exe       \
                 .\Release\DeletePass.exe           \
                 .\Release\DeleteZeroNameLength.exe \
                 .\Release\FiniInvalidSig.exe       \
                 .\Release\FiniNullContext.exe      \
                 .\Release\FiniNullFolder.exe       \
                 .\Release\FiniPass.exe             \
                 .\Release\GetInvalidSig.exe        \
                 .\Release\GetNullContext.exe       \
                 .\Release\GetNullDescriptor.exe    \
                 .\Release\GetNullFolder.exe        \
                 .\Release\GetNullName.exe          \
                 .\Release\GetPass.exe              \
                 .\Release\GetZeroNameLength.exe    \
                 .\Release\InitNullContext.exe      \
                 .\Release\InitNullFolder.exe       \
                 .\Release\InitNullName.exe         \
                 .\Release\InitNullParentOffset.exe \
                 .\Release\InitPass.exe             \
                 .\Release\InitZeroBlocks.exe       \
                 .\Release\InitZeroNameLength.exe   \
                 .\Release\InsertInvalidSig.exe     \
                 .\Release\InsertNullContext.exe    \
                 .\Release\InsertNullFolder.exe     \
                 .\Release\InsertNullName.exe       \
                 .\Release\InsertNullOrigName.exe   \
                 .\Release\InsertPass.exe           \
                 .\Release\InsertZeroBlocks.exe     \
                 .\Release\InsertZeroNameLength.exe \
                 .\Release\Tests.exe                \
                 .\Release\CloseNullContext.exe     \
                 .\Release\CloseNullDescriptor.exe  \
                 .\Release\ClosePass.exe            \
                 .\Release\CreateNullContext.exe    \
                 .\Release\CreateNullFolder.exe     \
                 .\Release\CreateNullName.exe       \
                 .\Release\CreatePass.exe           \
                 .\Release\CreateWrongType.exe      \
                 .\Release\DestroyNullContext.exe   \
                 .\Release\DestroyNullFolder.exe    \
                 .\Release\DestroyNullName.exe      \
                 .\Release\DestroyPass.exe          \
                 .\Release\OpenNullContext.exe      \
                 .\Release\OpenNullDescriptor.exe   \
                 .\Release\OpenNullFolder.exe       \
                 .\Release\OpenNullName.exe         \
                 .\Release\OpenPass.exe             \
                 .\Release\RemoveNullContext.exe    \
                 .\Release\RemoveNullFolder.exe     \
                 .\Release\RemoveNullName.exe       \
                 .\Release\RemovePass.exe           \
                 .\Release\RemoveZeroLength.exe     

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)
#

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

