# Copyright (C) 2008-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

all: 

check_PROGRAMS =                             \
        $(DIR_RELEASE)\CopyNullContext.exe        \
        $(DIR_RELEASE)\CopyNullHashItem.exe       \
        $(DIR_RELEASE)\CopyNullName.exe           \
        $(DIR_RELEASE)\CopyNullNewMap.exe         \
        $(DIR_RELEASE)\CopyNullOldMap.exe         \
        $(DIR_RELEASE)\CopyPass.exe               \
        $(DIR_RELEASE)\DeleteNullContext.exe      \
        $(DIR_RELEASE)\DeleteNullHash.exe         \
        $(DIR_RELEASE)\DeleteNullKey.exe          \
        $(DIR_RELEASE)\DeletePass.exe             \
        $(DIR_RELEASE)\DeleteZeroKeyLength.exe    \
        $(DIR_RELEASE)\EmptyNullContext.exe       \
        $(DIR_RELEASE)\EmptyNullMap.exe           \
        $(DIR_RELEASE)\EmptyPass.exe              \
        $(DIR_RELEASE)\FiniNullContext.exe        \
        $(DIR_RELEASE)\FiniNullHash.exe           \
        $(DIR_RELEASE)\FiniPass.exe               \
        $(DIR_RELEASE)\GetFirstNullContext.exe    \
        $(DIR_RELEASE)\GetFirstNullHash.exe       \
        $(DIR_RELEASE)\GetFirstNullItem.exe       \
        $(DIR_RELEASE)\GetFirstPass.exe           \
        $(DIR_RELEASE)\GetFirstWrongKeyLength.exe \
        $(DIR_RELEASE)\GetFirstWrongLength.exe    \
        $(DIR_RELEASE)\GetNextNullContext.exe     \
        $(DIR_RELEASE)\GetNextNullHash.exe        \
        $(DIR_RELEASE)\GetNextNullItem.exe        \
        $(DIR_RELEASE)\GetNextPass.exe            \
        $(DIR_RELEASE)\GetNextWrongKeyLength.exe  \
        $(DIR_RELEASE)\GetNextWrongLength.exe     \
        $(DIR_RELEASE)\GetNullContext.exe         \
        $(DIR_RELEASE)\GetNullHash.exe            \
        $(DIR_RELEASE)\GetNullItem.exe            \
        $(DIR_RELEASE)\GetNullKey.exe             \
        $(DIR_RELEASE)\GetPass.exe                \
        $(DIR_RELEASE)\GetWrongLength.exe         \
        $(DIR_RELEASE)\GetZeroKeyLength.exe       \
        $(DIR_RELEASE)\InitNullContext.exe        \
        $(DIR_RELEASE)\InitNullDataDef.exe        \
        $(DIR_RELEASE)\InitNullDefinition.exe     \
        $(DIR_RELEASE)\InitNullHash.exe           \
        $(DIR_RELEASE)\InitNullHashItem.exe       \
        $(DIR_RELEASE)\InitNullKeyDef.exe         \
        $(DIR_RELEASE)\InitNullName.exe           \
        $(DIR_RELEASE)\InitNullParent.exe         \
        $(DIR_RELEASE)\InitNullStatus.exe         \
        $(DIR_RELEASE)\InitPass.exe               \
        $(DIR_RELEASE)\InitZeroBlocks.exe         \
        $(DIR_RELEASE)\InitZeroLength.exe         \
        $(DIR_RELEASE)\InsertNullContext.exe      \
        $(DIR_RELEASE)\InsertNullHash.exe         \
        $(DIR_RELEASE)\InsertNullItem.exe         \
        $(DIR_RELEASE)\InsertNullKey.exe          \
        $(DIR_RELEASE)\InsertPass.exe             \
        $(DIR_RELEASE)\InsertZeroLengthItem.exe   \
        $(DIR_RELEASE)\InsertZeroLengthKey.exe    \
        $(DIR_RELEASE)\ReleaseNullContext.exe     \
        $(DIR_RELEASE)\ReleaseNullHash.exe        \
        $(DIR_RELEASE)\ReleaseNullItem.exe        \
        $(DIR_RELEASE)\ReleasePass.exe            \
        $(DIR_RELEASE)\ReplaceNullContext.exe     \
        $(DIR_RELEASE)\ReplaceNullHash.exe        \
        $(DIR_RELEASE)\ReplaceNullItem.exe        \
        $(DIR_RELEASE)\ReplaceNullKey.exe         \
        $(DIR_RELEASE)\ReplacePass.exe            \
        $(DIR_RELEASE)\ReplaceZeroLengthItem.exe  \
        $(DIR_RELEASE)\ReplaceZeroLengthKey.exe   \
        $(DIR_RELEASE)\StatusNullHash.exe         \
        $(DIR_RELEASE)\StatusNullStatus.exe       \
        $(DIR_RELEASE)\StatusPass.exe             

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q $(CLEANFILES)

