/*
 * This file was generated by the program errorParser
 * using the input file photon.xml.
 * Date: Tue Nov 18 16:58:38 2008.
 *
 * The version of this interface is 0.4.
 *
 * Copyright (C) 2006-2008 Daniel Prevost
 *
 * This file is part of Photon (photonsoftware.org).
 *
 * This file may be distributed and/or modified under the terms of the
 * GNU General Public License version 2 as published by the Free
 * Software Foundation and appearing in the file COPYING included in
 * the packaging of this library.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 */

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

using System;

namespace Photon
{
    enum PhotonErrors
    {
        OK = 0,

        INTERNAL_ERROR = 666,

        ENGINE_BUSY = 1,

        NOT_ENOUGH_PSO_MEMORY = 2,

        NOT_ENOUGH_HEAP_MEMORY = 3,

        NOT_ENOUGH_RESOURCES = 4,

        WRONG_TYPE_HANDLE = 5,

        NULL_HANDLE = 6,

        NULL_POINTER = 7,

        INVALID_LENGTH = 8,

        PROCESS_ALREADY_INITIALIZED = 21,

        PROCESS_NOT_INITIALIZED = 22,

        INVALID_QUASAR_ADDRESS = 23,

        INCOMPATIBLE_VERSIONS = 24,

        SOCKET_ERROR = 25,

        CONNECT_ERROR = 26,

        SEND_ERROR = 27,

        RECEIVE_ERROR = 28,

        BACKSTORE_FILE_MISSING = 29,

        ERROR_OPENING_MEMORY = 30,

        LOGFILE_ERROR = 41,

        SESSION_CANNOT_GET_LOCK = 42,

        SESSION_IS_TERMINATED = 43,

        INVALID_OBJECT_NAME = 51,

        NO_SUCH_OBJECT = 52,

        NO_SUCH_FOLDER = 53,

        OBJECT_ALREADY_PRESENT = 54,

        IS_EMPTY = 55,

        WRONG_OBJECT_TYPE = 56,

        OBJECT_CANNOT_GET_LOCK = 57,

        REACHED_THE_END = 58,

        INVALID_ITERATOR = 59,

        OBJECT_NAME_TOO_LONG = 60,

        FOLDER_IS_NOT_EMPTY = 61,

        ITEM_ALREADY_PRESENT = 62,

        NO_SUCH_ITEM = 63,

        OBJECT_IS_DELETED = 64,

        OBJECT_NOT_INITIALIZED = 65,

        ITEM_IS_IN_USE = 66,

        ITEM_IS_DELETED = 67,

        OBJECT_IS_IN_USE = 69,

        OBJECT_IS_READ_ONLY = 70,

        NOT_ALL_EDIT_ARE_CLOSED = 71,

        A_SINGLE_UPDATER_IS_ALLOWED = 72,

        INVALID_NUM_FIELDS = 101,

        INVALID_FIELD_TYPE = 102,

        INVALID_FIELD_LENGTH_INT = 103,

        INVALID_FIELD_LENGTH = 104,

        INVALID_FIELD_NAME = 105,

        DUPLICATE_FIELD_NAME = 106,

        INVALID_PRECISION = 107,

        INVALID_SCALE = 108,

        INVALID_KEY_DEF = 109,

        XML_READ_ERROR = 201,

        XML_INVALID_ROOT = 202,

        XML_NO_SCHEMA_LOCATION = 203,

        XML_PARSER_CONTEXT_FAILED = 204,

        XML_PARSE_SCHEMA_FAILED = 205,

        XML_VALID_CONTEXT_FAILED = 206,

        XML_VALIDATION_FAILED = 207,

        SEM_DESTROY_ERROR = 601
    }
}

