# Copyright (C) 2007-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

all: 

CLEANFILES = *~ 

check_PROGRAMS =                           \
        $(DIR_RELEASE)\FiniNullBitmap.exe       \
        $(DIR_RELEASE)\FiniPass.exe             \
        $(DIR_RELEASE)\GetLengthPass.exe        \
        $(DIR_RELEASE)\GetLengthPowerOfTwo7.exe \
        $(DIR_RELEASE)\GetLengthPowerOfTwo9.exe \
        $(DIR_RELEASE)\GetLengthZeroLength.exe  \
        $(DIR_RELEASE)\GetLengthZeroGranu.exe   \
        $(DIR_RELEASE)\InitNullBitmap.exe       \
        $(DIR_RELEASE)\InitNullOffset.exe       \
        $(DIR_RELEASE)\InitPass.exe             \
        $(DIR_RELEASE)\InitPowerOfTwo7.exe      \
        $(DIR_RELEASE)\InitPowerOfTwo9.exe      \
        $(DIR_RELEASE)\InitZeroGranu.exe        \
        $(DIR_RELEASE)\InitZeroLength.exe       \
        $(DIR_RELEASE)\IsFreeNullBitmap.exe     \
        $(DIR_RELEASE)\IsFreeNullOffset.exe     \
        $(DIR_RELEASE)\IsFreePass.exe           \
        $(DIR_RELEASE)\SetAllocNullBitmap.exe   \
        $(DIR_RELEASE)\SetAllocNullOffset.exe   \
        $(DIR_RELEASE)\SetAllocPass.exe         \
        $(DIR_RELEASE)\SetAllocZeroLength.exe   \
        $(DIR_RELEASE)\SetFreeNullBitmap.exe    \
        $(DIR_RELEASE)\SetFreeNullOffset.exe    \
        $(DIR_RELEASE)\SetFreePass.exe          

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q $(CLEANFILES)

