# Copyright (C) 2007-2008 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

check_PROGRAMS =                             \
        .\Release\CopyNullContext.exe        \
        .\Release\CopyNullNewHash.exe        \
        .\Release\CopyNullOldHash.exe        \
        .\Release\CopyPass.exe               \
        .\Release\CopyPassSameLength.exe     \
        .\Release\DeleteNullContext.exe      \
        .\Release\DeleteNullHash.exe         \
        .\Release\DeleteNullKey.exe          \
        .\Release\DeletePass.exe             \
        .\Release\DeleteZeroLength.exe       \
        .\Release\EmptyNullContext.exe       \
        .\Release\EmptyNullHash.exe          \
        .\Release\EmptyPass.exe              \
        .\Release\FiniNullHash.exe           \
        .\Release\FiniPass.exe               \
        .\Release\GetFirstNullHash.exe       \
        .\Release\GetFirstNullOffset.exe     \
        .\Release\GetFirstPass.exe           \
        .\Release\GetNextNullHash.exe        \
        .\Release\GetNextNullNextOffset.exe  \
        .\Release\GetNextNullPrevOffset.exe  \
        .\Release\GetNextPass.exe            \
        .\Release\GetNullBucket.exe          \
        .\Release\GetNullContext.exe         \
        .\Release\GetNullHash.exe            \
        .\Release\GetNullItem.exe            \
        .\Release\GetNullKey.exe             \
        .\Release\GetPass.exe                \
        .\Release\GetZeroKeyLength.exe       \
        .\Release\InitNullContext.exe        \
        .\Release\InitNullHash.exe           \
        .\Release\InitNullOffset.exe         \
        .\Release\InitPass.exe               \
        .\Release\InsertNullContext.exe      \
        .\Release\InsertNullData.exe         \
        .\Release\InsertNullHash.exe         \
        .\Release\InsertNullKey.exe          \
        .\Release\InsertPass.exe             \
        .\Release\InsertZeroDataLength.exe   \
        .\Release\InsertZeroKeyLength.exe    \
        .\Release\ResizeNullContext.exe      \
        .\Release\ResizeNullHash.exe         \
        .\Release\ResizePass.exe             \
        .\Release\UpdateNullContext.exe      \
        .\Release\UpdateNullData.exe         \
        .\Release\UpdateNullHash.exe         \
        .\Release\UpdateNullKey.exe          \
        .\Release\UpdatePass.exe             \
        .\Release\UpdateZeroDataLength.exe   \
        .\Release\UpdateZeroKeyLength.exe    

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

