# Copyright (C) 2006-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

RELEASE = Release2005
DEBUG = Debug2005
DLL_RELEASE = ..\..\..\Release2005
DLL_DEBUG = ..\..\..\Debug2005

all: 

CLEANFILES = *~ 

check_PROGRAMS =                              \
        $(DIR_RELEASE)\BackStatusInvalidSig.exe    \
        $(DIR_RELEASE)\BackStatusMemNull.exe       \
        $(DIR_RELEASE)\BackStatusNameEmpty.exe     \
        $(DIR_RELEASE)\BackStatusPass.exe          \
        $(DIR_RELEASE)\BackStatusStatusNull.exe    \
        $(DIR_RELEASE)\CloseNullError.exe          \
        $(DIR_RELEASE)\CloseInvalidSig.exe         \
        $(DIR_RELEASE)\CloseMemNull.exe            \
        $(DIR_RELEASE)\ClosePass.exe               \
        $(DIR_RELEASE)\CopyPass.exe                \
        $(DIR_RELEASE)\CreateBackNullError.exe     \
        $(DIR_RELEASE)\CreateBackInvalidSig.exe    \
        $(DIR_RELEASE)\CreateBackInvLength.exe     \
        $(DIR_RELEASE)\CreateBackMemNull.exe       \
        $(DIR_RELEASE)\CreateBackNameEmpty.exe     \
        $(DIR_RELEASE)\CreateBackPass.exe          \
        $(DIR_RELEASE)\CreateBackPerm0000.exe      \
        $(DIR_RELEASE)\CreateBackPerm0200.exe      \
        $(DIR_RELEASE)\CreateBackPerm0400.exe      \
        $(DIR_RELEASE)\CreateBackPerm0500.exe      \
        $(DIR_RELEASE)\FiniInvalidSig.exe          \
        $(DIR_RELEASE)\FiniNullMem.exe             \
        $(DIR_RELEASE)\FiniPass.exe                \
        $(DIR_RELEASE)\InitLengthPositive.exe      \
        $(DIR_RELEASE)\InitMemNull.exe             \
        $(DIR_RELEASE)\InitNameEmpty.exe           \
        $(DIR_RELEASE)\InitNameNull.exe            \
        $(DIR_RELEASE)\InitPass.exe                \
        $(DIR_RELEASE)\OpenAddrNull.exe            \
        $(DIR_RELEASE)\OpenNullError.exe           \
        $(DIR_RELEASE)\OpenInvalidLength.exe       \
        $(DIR_RELEASE)\OpenInvalidSig.exe          \
        $(DIR_RELEASE)\OpenMemNull.exe             \
        $(DIR_RELEASE)\OpenNameEmpty.exe           \
        $(DIR_RELEASE)\OpenPass.exe                \
        $(DIR_RELEASE)\ReadOnlyNullError.exe       \
        $(DIR_RELEASE)\ReadOnlyInvalidBaseAddr.exe \
        $(DIR_RELEASE)\ReadOnlyInvalidSig.exe      \
        $(DIR_RELEASE)\ReadOnlyMemNull.exe         \
        $(DIR_RELEASE)\ReadOnlyPass.exe            \
        $(DIR_RELEASE)\ReadOnlyTryWrite.exe        \
        $(DIR_RELEASE)\ReadWriteNullError.exe      \
        $(DIR_RELEASE)\ReadWriteInvalidSig.exe     \
        $(DIR_RELEASE)\ReadWriteInvBaseAddr.exe    \
        $(DIR_RELEASE)\ReadWriteMemNull.exe        \
        $(DIR_RELEASE)\ReadWritePass.exe           \
        $(DIR_RELEASE)\SynchNullError.exe          \
        $(DIR_RELEASE)\SynchInvalidBaseAddr.exe    \
        $(DIR_RELEASE)\SynchInvalidSig.exe         \
        $(DIR_RELEASE)\SynchMemNull.exe            \
        $(DIR_RELEASE)\SynchPass.exe               \
        $(DIR_RELEASE)\Tests.exe                   

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)\Tests
	-@rmdir /Q $(DIR_DEBUG)\Tests
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)\Tests
	-@rmdir /Q $(DIR_RELEASE)\Tests
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q ProjectFiles\*.dep
	-@erase /Q ProjectFiles\*.plg
	-@erase /Q ProjectFiles\*.mak
	-@erase /Q $(CLEANFILES)

