/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_Session */

#ifndef _Included_org_photon_Session
#define _Included_org_photon_Session
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_Session
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_Session_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_photon_Session
 * Method:    psoCommit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Session_psoCommit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_photon_Session
 * Method:    psoCreateObject
 * Signature: (JLjava/lang/String;Lorg/photon/ObjectDefinition;Lorg/photon/KeyDefinition;[Lorg/photon/FieldDefinition;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Session_psoCreateObject
  (JNIEnv *, jobject, jlong, jstring, jobject, jobject, jobjectArray);

/*
 * Class:     org_photon_Session
 * Method:    psoDestroyObject
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Session_psoDestroyObject
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_photon_Session
 * Method:    psoFini
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Session_psoFini
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_photon_Session
 * Method:    psoGetDefinition
 * Signature: (JLjava/lang/String;Lorg/photon/Definition;Lorg/photon/ObjectDefinition;Lorg/photon/KeyDefinition;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Session_psoGetDefinition
  (JNIEnv *, jobject, jlong, jstring, jobject, jobject, jobject);

/*
 * Class:     org_photon_Session
 * Method:    psoGetInfo
 * Signature: (JLorg/photon/Info;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Session_psoGetInfo
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_Session
 * Method:    psoGetStatus
 * Signature: (JLjava/lang/String;Lorg/photon/ObjectStatus;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Session_psoGetStatus
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     org_photon_Session
 * Method:    psoInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_photon_Session_psoInit
  (JNIEnv *, jobject);

/*
 * Class:     org_photon_Session
 * Method:    psoRollback
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Session_psoRollback
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
