/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_PhotonFolder */

#ifndef _Included_org_photon_PhotonFolder
#define _Included_org_photon_PhotonFolder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_PhotonFolder
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_PhotonFolder_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_photon_PhotonFolder
 * Method:    folderCreateObject
 * Signature: (JLjava/lang/String;Lorg/photon/ObjectDefinition;Lorg/photon/KeyDefinition;[Lorg/photon/FieldDefinition;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_PhotonFolder_folderCreateObject
  (JNIEnv *, jobject, jlong, jstring, jobject, jobject, jobjectArray);

/*
 * Class:     org_photon_PhotonFolder
 * Method:    folderCreateObjectXML
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_PhotonFolder_folderCreateObjectXML
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_photon_PhotonFolder
 * Method:    folderDestroyObject
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_PhotonFolder_folderDestroyObject
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_photon_PhotonFolder
 * Method:    folderFini
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_photon_PhotonFolder_folderFini
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_photon_PhotonFolder
 * Method:    folderGetFirst
 * Signature: (JLorg/photon/FolderEntry;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_PhotonFolder_folderGetFirst
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_PhotonFolder
 * Method:    folderGetNext
 * Signature: (JLorg/photon/FolderEntry;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_PhotonFolder_folderGetNext
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_PhotonFolder
 * Method:    folderInit
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_PhotonFolder_folderInit
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_photon_PhotonFolder
 * Method:    folderStatus
 * Signature: (JLorg/photon/ObjStatus;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_PhotonFolder_folderStatus
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
