/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_KeyDefBuilderUser */

#ifndef _Included_org_photon_KeyDefBuilderUser
#define _Included_org_photon_KeyDefBuilderUser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_KeyDefBuilderUser
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_KeyDefBuilderUser_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_photon_KeyDefBuilderUser
 * Method:    psoAddKeyField
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_KeyDefBuilderUser_psoAddKeyField
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
