/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_ObjectType */

#ifndef _Included_org_photon_ObjectType
#define _Included_org_photon_ObjectType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_ObjectType
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_ObjectType_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
