/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_DataDefBuilderUser */

#ifndef _Included_org_photon_DataDefBuilderUser
#define _Included_org_photon_DataDefBuilderUser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_DataDefBuilderUser
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_DataDefBuilderUser_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_photon_DataDefBuilderUser
 * Method:    psoAddField
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_DataDefBuilderUser_psoAddField
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
