/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_PhotonSession */

#ifndef _Included_org_photon_PhotonSession
#define _Included_org_photon_PhotonSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_PhotonSession
 * Method:    initSession
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_photon_PhotonSession_initSession
  (JNIEnv *, jobject);

/*
 * Class:     org_photon_PhotonSession
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_PhotonSession_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
