/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_Info */

#ifndef _Included_org_photon_Info
#define _Included_org_photon_Info
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_Info
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_Info_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
