/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_Queue */

#ifndef _Included_org_photon_Queue
#define _Included_org_photon_Queue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_Queue
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_Queue_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_photon_Queue
 * Method:    psoFini
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_photon_Queue_psoFini
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_photon_Queue
 * Method:    psoGetFirst
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Queue_psoGetFirst
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_Queue
 * Method:    psoGetNext
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Queue_psoGetNext
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_Queue
 * Method:    psoGetStatus
 * Signature: (JLorg/photon/ObjectStatus;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Queue_psoGetStatus
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_Queue
 * Method:    psoInit
 * Signature: (Lorg/photon/Session;Ljava/lang/String;Lorg/photon/Definition;Lorg/photon/ObjectDefinition;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Queue_psoInit
  (JNIEnv *, jobject, jobject, jstring, jobject, jobject);

/*
 * Class:     org_photon_Queue
 * Method:    psoPop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Queue_psoPop
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_Queue
 * Method:    psoPush
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Queue_psoPush
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_Queue
 * Method:    psoPushNow
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Queue_psoPushNow
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
