/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_PhotonProcess */

#ifndef _Included_org_photon_PhotonProcess
#define _Included_org_photon_PhotonProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_PhotonProcess
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_PhotonProcess_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_photon_PhotonProcess
 * Method:    fini
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_PhotonProcess_fini
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
