/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_KeyDefBuilderODBC */

#ifndef _Included_org_photon_KeyDefBuilderODBC
#define _Included_org_photon_KeyDefBuilderODBC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_KeyDefBuilderODBC
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_KeyDefBuilderODBC_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_photon_KeyDefBuilderODBC
 * Method:    psoAddKeyField
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_org_photon_KeyDefBuilderODBC_psoAddKeyField
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     org_photon_KeyDefBuilderODBC
 * Method:    psoGetLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_photon_KeyDefBuilderODBC_psoGetLength
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
