/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_RawQueue */

#ifndef _Included_org_photon_RawQueue
#define _Included_org_photon_RawQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_RawQueue
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_RawQueue_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_photon_RawQueue
 * Method:    psoClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_photon_RawQueue_psoClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_photon_RawQueue
 * Method:    psoDataDefinition
 * Signature: (JLorg/photon/DataDefinition;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_RawQueue_psoDataDefinition
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_RawQueue
 * Method:    psoGetFirst
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_photon_RawQueue_psoGetFirst
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_photon_RawQueue
 * Method:    psoGetNext
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_photon_RawQueue_psoGetNext
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_photon_RawQueue
 * Method:    psoGetRecordDefinition
 * Signature: (JLorg/photon/DataDefinition;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_RawQueue_psoGetRecordDefinition
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_RawQueue
 * Method:    psoGetStatus
 * Signature: (JLorg/photon/ObjectStatus;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_RawQueue_psoGetStatus
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_RawQueue
 * Method:    psoOpen
 * Signature: (Lorg/photon/Session;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_RawQueue_psoOpen
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_photon_RawQueue
 * Method:    psoPop
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_photon_RawQueue_psoPop
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_photon_RawQueue
 * Method:    psoPush
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_photon_RawQueue_psoPush
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_photon_RawQueue
 * Method:    psoPushNow
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_photon_RawQueue_psoPushNow
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
