# Copyright (C) 2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


classes = Java(target = 'classes', source = 'java_src/photon' )
Java(target = 'classes', source = 'java_src/serializer' )
Java(target = 'classes', source = 'java_src/Tests' )

JavaH(target = 'include', source = classes )

# http://www.scons.org/wiki/JavaNativeInterface
