# Copyright (C) 2007-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include .\Makefile.inc.win32.2005

#
# Override the values in Makefile.inc.Win32
#
LDD_FLAGS = $(W32_SYS_LIBS)     photon.lib photonNucleus.lib photonCommon.lib /nologo /subsystem:console /machine:I386 /libpath:"../../Release" 
LDD_FLAGS_DEBUG=$(W32_SYS_LIBS) photon.lib photonNucleus.lib photonCommon.lib /nologo /subsystem:console /machine:I386 /libpath:"../../Debug" 
CFLAGS_DEBUG=   /nologo /MDd /W4     /I "../.." /I "../../include" /D "WIN32" /D "_DEBUG" /D "_CONSOLE" /D "_MBCS" /Fo"$(DIR_DEBUG)\\" 
CFLAGS_RELEASE= /nologo /MD  /W4 /O2 /I "../.." /I "../../include" /D "WIN32" /D "NDEBUG" /D "_CONSOLE" /D "_MBCS" /Fo"$(DIR_RELEASE)\\" 

all: 

CLEANFILES = *~ 

check_PROGRAMS =                                

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cd FastMap    && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Folder     && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd HashMap    && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Lifo       && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Queue      && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Process    && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Session    && nmake -f Makefile.win32 check VBS_VERBOSE=$(VBS_VERBOSE) && cd ..

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cd FastMap    && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Folder     && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd HashMap    && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Lifo       && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Queue      && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Process    && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..
	cd Session    && nmake -f Makefile.win32 checkdebug VBS_VERBOSE=$(VBS_VERBOSE) && cd ..

clean:
	cd FastMap    && nmake -f Makefile.win32 clean && cd ..
	cd Folder     && nmake -f Makefile.win32 clean && cd ..
	cd HashMap    && nmake -f Makefile.win32 clean && cd ..
	cd Lifo       && nmake -f Makefile.win32 clean && cd ..
	cd Queue      && nmake -f Makefile.win32 clean && cd ..
	cd Process    && nmake -f Makefile.win32 clean && cd ..
	cd Session    && nmake -f Makefile.win32 clean && cd ..
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q $(CLEANFILES)

