# Copyright (C) 2007-2008 Daniel Prevost <dprevost@users.sourceforge.net>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

check_PROGRAMS =                   \
   .\Release\FiniNullContext.exe   \
   .\Release\FiniNullObj.exe       \
   .\Release\FiniPass.exe          \
   .\Release\FreeNullContext.exe   \
   .\Release\FreeNullObj.exe       \
   .\Release\FreeNullPtr.exe       \
   .\Release\FreePass.exe          \
   .\Release\FreeZeroBytes.exe     \
   .\Release\InitInvType.exe       \
   .\Release\InitNullGroup.exe     \
   .\Release\InitNullObj.exe       \
   .\Release\InitPass.exe          \
   .\Release\InitZeroPages.exe     \
   .\Release\InitZeroType.exe      \
   .\Release\MallocNullContext.exe \
   .\Release\MallocNullObj.exe     \
   .\Release\MallocPass.exe        \
   .\Release\MallocZeroBytes.exe   \
   .\Release\StatusNullMemObj.exe  \
   .\Release\StatusNullStatus.exe  \
   .\Release\StatusPass.exe        

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

