# Copyright (C) 2007-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

CLEANFILES = $(CLEANFILES) *.tlog

check_PROGRAMS =                      \
        .\Release\CloseNoInit.exe     \
        .\Release\CloseNULLLog.exe    \
        .\Release\CloseNULLError.exe  \
        .\Release\ClosePass.exe       \
        .\Release\InitNULLDir.exe     \
        .\Release\InitNULLError.exe   \
        .\Release\InitNULLLog.exe     \
        .\Release\InitNULLSession.exe \
        .\Release\InitPass.exe        \
        .\Release\LogNoInit.exe       \
        .\Release\LogNULLError.exe    \
        .\Release\LogNULLLog.exe      \
        .\Release\LogPass.exe         \
        .\Release\LogFileTest.exe

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

