# Copyright (C) 2006-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

check_PROGRAMS =                              \
        .\Release\CloseNullContext.exe        \
        .\Release\CloseNullItem.exe           \
        .\Release\ClosePass.exe               \
        .\Release\CreateInvalidNameLength.exe \
        .\Release\CreateNullContext.exe       \
        .\Release\CreateNullDefinition.exe    \
        .\Release\CreateNullFolder.exe        \
        .\Release\CreateNullName.exe          \
        .\Release\CreatePass.exe              \
        .\Release\CreateWrongType.exe         \
        .\Release\DestroyNullContext.exe      \
        .\Release\DestroyNullFolder.exe       \
        .\Release\DestroyNullName.exe         \
        .\Release\DestroyPass.exe             \
        .\Release\EditNullContext.exe         \
        .\Release\EditNullFolder.exe          \
        .\Release\EditNullItem.exe            \
        .\Release\EditNullName.exe            \
        .\Release\EditPass.exe                \
        .\Release\EditWrongLength.exe         \
        .\Release\EditWrongType.exe           \
        .\Release\EditZeroLength.exe          \
        .\Release\GetDefNullContext.exe       \
        .\Release\GetDefNullDataDef.exe       \
        .\Release\GetDefNullDef.exe           \
        .\Release\GetDefNullFolder.exe        \
        .\Release\GetDefNullKeyDef.exe        \
        .\Release\GetDefNullName.exe          \
        .\Release\GetDefPass.exe              \
        .\Release\OpenNullContext.exe         \
        .\Release\OpenNullItem.exe            \
        .\Release\OpenNullFolder.exe          \
        .\Release\OpenNullName.exe            \
        .\Release\OpenPass.exe                \
        .\Release\OpenWrongLength.exe         \
        .\Release\OpenWrongType.exe           \
        .\Release\OpenZeroLength.exe          \
        .\Release\StatusNullContext.exe       \
        .\Release\StatusNullFolder.exe        \
        .\Release\StatusNullName.exe          \
        .\Release\StatusNullStatus.exe        \
        .\Release\StatusPass.exe              

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

