# Copyright (C) 2006-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

all: 

check_PROGRAMS =                                   \
        $(DIR_RELEASE)\CloseNullContext.exe        \
        $(DIR_RELEASE)\CloseNullItem.exe           \
        $(DIR_RELEASE)\ClosePass.exe               \
        $(DIR_RELEASE)\CreateFolderInvLength.exe   \
        $(DIR_RELEASE)\CreateFolderNullContext.exe \
        $(DIR_RELEASE)\CreateFolderNullFolder.exe  \
        $(DIR_RELEASE)\CreateFolderNullName.exe    \
        $(DIR_RELEASE)\CreateFolderPass.exe        \
        $(DIR_RELEASE)\CreateInvalidNameLength.exe \
        $(DIR_RELEASE)\CreateNullContext.exe       \
        $(DIR_RELEASE)\CreateNullDefinition.exe    \
        $(DIR_RELEASE)\CreateNullFolder.exe        \
        $(DIR_RELEASE)\CreateNullName.exe          \
        $(DIR_RELEASE)\CreatePass.exe              \
        $(DIR_RELEASE)\CreateWrongType.exe         \
        $(DIR_RELEASE)\DestroyNullContext.exe      \
        $(DIR_RELEASE)\DestroyNullFolder.exe       \
        $(DIR_RELEASE)\DestroyNullName.exe         \
        $(DIR_RELEASE)\DestroyPass.exe             \
        $(DIR_RELEASE)\EditNullContext.exe         \
        $(DIR_RELEASE)\EditNullFolder.exe          \
        $(DIR_RELEASE)\EditNullItem.exe            \
        $(DIR_RELEASE)\EditNullName.exe            \
        $(DIR_RELEASE)\EditPass.exe                \
        $(DIR_RELEASE)\EditWrongLength.exe         \
        $(DIR_RELEASE)\EditWrongType.exe           \
        $(DIR_RELEASE)\EditZeroLength.exe          \
        $(DIR_RELEASE)\GetDefNullContext.exe       \
        $(DIR_RELEASE)\GetDefNullDataDef.exe       \
        $(DIR_RELEASE)\GetDefNullDef.exe           \
        $(DIR_RELEASE)\GetDefNullFolder.exe        \
        $(DIR_RELEASE)\GetDefNullKeyDef.exe        \
        $(DIR_RELEASE)\GetDefNullName.exe          \
        $(DIR_RELEASE)\GetDefPass.exe              \
        $(DIR_RELEASE)\OpenNullContext.exe         \
        $(DIR_RELEASE)\OpenNullItem.exe            \
        $(DIR_RELEASE)\OpenNullFolder.exe          \
        $(DIR_RELEASE)\OpenNullName.exe            \
        $(DIR_RELEASE)\OpenPass.exe                \
        $(DIR_RELEASE)\OpenWrongLength.exe         \
        $(DIR_RELEASE)\OpenWrongType.exe           \
        $(DIR_RELEASE)\OpenZeroLength.exe          \
        $(DIR_RELEASE)\StatusNullContext.exe       \
        $(DIR_RELEASE)\StatusNullFolder.exe        \
        $(DIR_RELEASE)\StatusNullName.exe          \
        $(DIR_RELEASE)\StatusNullStatus.exe        \
        $(DIR_RELEASE)\StatusPass.exe              

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q $(CLEANFILES)

