# Copyright (C) 2007-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

all: 

check_PROGRAMS =                            \
        $(DIR_RELEASE)\AddInvalidSig.exe         \
        $(DIR_RELEASE)\AddNullChildOffset.exe    \
        $(DIR_RELEASE)\AddNullContext.exe        \
        $(DIR_RELEASE)\AddNullParentOffset.exe   \
        $(DIR_RELEASE)\AddNullTx.exe             \
        $(DIR_RELEASE)\AddPass.exe               \
        $(DIR_RELEASE)\CommitInvalidSig.exe      \
        $(DIR_RELEASE)\CommitNullContext.exe     \
        $(DIR_RELEASE)\CommitNullTx.exe          \
        $(DIR_RELEASE)\CommitPass.exe            \
        $(DIR_RELEASE)\FiniInvalidSig.exe        \
        $(DIR_RELEASE)\FiniNullContext.exe       \
        $(DIR_RELEASE)\FiniNullTx.exe            \
        $(DIR_RELEASE)\FiniPass.exe              \
        $(DIR_RELEASE)\InitNullContext.exe       \
        $(DIR_RELEASE)\InitNullTx.exe            \
        $(DIR_RELEASE)\InitPass.exe              \
        $(DIR_RELEASE)\InitZeroBlocks.exe        \
        $(DIR_RELEASE)\RemoveLastInvalidSig.exe  \
        $(DIR_RELEASE)\RemoveLastNullContext.exe \
        $(DIR_RELEASE)\RemoveLastNullTx.exe      \
        $(DIR_RELEASE)\RemoveLastPass.exe        \
        $(DIR_RELEASE)\RollbackInvalidSig.exe    \
        $(DIR_RELEASE)\RollbackNullContext.exe   \
        $(DIR_RELEASE)\RollbackNullTx.exe        \
        $(DIR_RELEASE)\RollbackPass.exe          \
        $(DIR_RELEASE)\TestFolder.exe            \
        $(DIR_RELEASE)\TestHashMap.exe           \
        $(DIR_RELEASE)\TestQueue.exe             

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q $(CLEANFILES)

