# Copyright (C) 2006-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

RELEASE = Release2005
DEBUG = Debug2005
DLL_RELEASE = ..\..\..\Release2005
DLL_DEBUG = ..\..\..\Debug2005

all: 

CLEANFILES = *~ 

check_PROGRAMS =                           \
        $(DIR_RELEASE)\AcquireInvalidSig.exe    \
        $(DIR_RELEASE)\AcquireNullLock.exe      \
        $(DIR_RELEASE)\AcquirePass.exe          \
        $(DIR_RELEASE)\AcquireZeroValue.exe     \
        $(DIR_RELEASE)\FiniInvalidSig.exe       \
        $(DIR_RELEASE)\FiniNullLock.exe         \
        $(DIR_RELEASE)\FiniPass.exe             \
        $(DIR_RELEASE)\InitNullLock.exe         \
        $(DIR_RELEASE)\InitPass.exe             \
        $(DIR_RELEASE)\IsItLockedInvalidSig.exe \
        $(DIR_RELEASE)\IsItLockedNullLock.exe   \
        $(DIR_RELEASE)\IsItLockedPass.exe       \
        $(DIR_RELEASE)\LockConcurrency.exe      \
        $(DIR_RELEASE)\LockTests.exe            \
        $(DIR_RELEASE)\ReleaseInvalidSig.exe    \
        $(DIR_RELEASE)\ReleaseNullLock.exe      \
        $(DIR_RELEASE)\ReleasePass.exe          \
        $(DIR_RELEASE)\TestPidInvalidSig.exe    \
        $(DIR_RELEASE)\TestPidNullLock.exe      \
        $(DIR_RELEASE)\TestPidPass.exe          \
        $(DIR_RELEASE)\TestPidZeroPid.exe       \
        $(DIR_RELEASE)\TryAcqInvalidSig.exe     \
        $(DIR_RELEASE)\TryAcqNullLock.exe       \
        $(DIR_RELEASE)\TryAcqPass.exe           \
        $(DIR_RELEASE)\TryAcqZeroValue.exe      

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)\LockConcurrency
	-@rmdir /Q $(DIR_DEBUG)\LockConcurrency
	-@erase /Q $(DIR_DEBUG)\LockTests
	-@rmdir /Q $(DIR_DEBUG)\LockTests
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)\LockConcurrency
	-@rmdir /Q $(DIR_RELEASE)\LockConcurrency
	-@erase /Q $(DIR_RELEASE)\LockTests
	-@rmdir /Q $(DIR_RELEASE)\LockTests
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q ProjectFiles\*.dep
	-@erase /Q ProjectFiles\*.plg
	-@erase /Q ProjectFiles\*.mak
	-@erase /Q $(CLEANFILES)

