# Copyright (C) 2006-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

CLEANFILES = *~ 

check_PROGRAMS =                           \
        .\Release\AcquireInvalidSig.exe    \
        .\Release\AcquireNullLock.exe      \
        .\Release\AcquirePass.exe          \
        .\Release\AcquireZeroValue.exe     \
        .\Release\FiniInvalidSig.exe       \
        .\Release\FiniNullLock.exe         \
        .\Release\FiniPass.exe             \
        .\Release\InitNullLock.exe         \
        .\Release\InitPass.exe             \
        .\Release\IsItLockedInvalidSig.exe \
        .\Release\IsItLockedNullLock.exe   \
        .\Release\IsItLockedPass.exe       \
        .\Release\LockConcurrency.exe      \
        .\Release\LockTests.exe            \
        .\Release\ReleaseInvalidSig.exe    \
        .\Release\ReleaseNullLock.exe      \
        .\Release\ReleasePass.exe          \
        .\Release\TestPidInvalidSig.exe    \
        .\Release\TestPidNullLock.exe      \
        .\Release\TestPidPass.exe          \
        .\Release\TestPidZeroPid.exe       \
        .\Release\TryAcqInvalidSig.exe     \
        .\Release\TryAcqNullLock.exe       \
        .\Release\TryAcqPass.exe           \
        .\Release\TryAcqZeroValue.exe      

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug\LockConcurrency
	-@rmdir /Q Debug\LockConcurrency
	-@erase /Q Debug\LockTests
	-@rmdir /Q Debug\LockTests
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release\LockConcurrency
	-@rmdir /Q Release\LockConcurrency
	-@erase /Q Release\LockTests
	-@rmdir /Q Release\LockTests
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q ProjectFiles\*.dep
	-@erase /Q ProjectFiles\*.plg
	-@erase /Q ProjectFiles\*.mak
	-@erase /Q $(CLEANFILES)

