/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_Photon */

#ifndef _Included_org_photon_Photon
#define _Included_org_photon_Photon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_Photon
 * Method:    psoInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_Photon_psoInit
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_photon_Photon
 * Method:    psoFini
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_Photon_psoFini
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
