/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_PhotonException */

#ifndef _Included_org_photon_PhotonException
#define _Included_org_photon_PhotonException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_photon_PhotonException_serialVersionUID
#define org_photon_PhotonException_serialVersionUID -3042686055658047285LL
#undef org_photon_PhotonException_serialVersionUID
#define org_photon_PhotonException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
