/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_BaseQueue */

#ifndef _Included_org_photon_BaseQueue
#define _Included_org_photon_BaseQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_BaseQueue
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_BaseQueue_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_photon_BaseQueue
 * Method:    psoClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_photon_BaseQueue_psoClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_photon_BaseQueue
 * Method:    psoDataDefinition
 * Signature: (JLorg/photon/DataDefinition;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_BaseQueue_psoDataDefinition
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_BaseQueue
 * Method:    psoGetFirst
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_photon_BaseQueue_psoGetFirst
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_photon_BaseQueue
 * Method:    psoGetNext
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_photon_BaseQueue_psoGetNext
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_photon_BaseQueue
 * Method:    psoGetRecordDefinition
 * Signature: (JLorg/photon/DataDefinition;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_BaseQueue_psoGetRecordDefinition
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_BaseQueue
 * Method:    psoGetStatus
 * Signature: (JLorg/photon/ObjectStatus;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_BaseQueue_psoGetStatus
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_photon_BaseQueue
 * Method:    psoOpen
 * Signature: (Lorg/photon/Session;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_photon_BaseQueue_psoOpen
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_photon_BaseQueue
 * Method:    psoPop
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_photon_BaseQueue_psoPop
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_photon_BaseQueue
 * Method:    psoPush
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_photon_BaseQueue_psoPush
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_photon_BaseQueue
 * Method:    psoPushNow
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_photon_BaseQueue_psoPushNow
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
