# Copyright (C) 2007-2008 Daniel Prevost <dprevost@users.sourceforge.net>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

###########################################################################
#
# Defines the main macros.
#
###########################################################################

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE 
NULL=nul
!ENDIF 

LINK32=link.exe

OUTDIR_RELEASE = .\Release
INTDIR_RELEASE = .\Release
OUTDIR_DEBUG   = .\Debug
INTDIR_DEBUG   = .\Debug

CLEANFILES = *~

W32_SYS_LIBS=kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib ws2_32.lib

LDD_FLAGS_RELEASE = $(W32_SYS_LIBS) vdsfCommon.lib /nologo /subsystem:console /machine:I386 /libpath:"..\..\Release" 
LDD_FLAGS_DEBUG   = $(W32_SYS_LIBS) vdsfCommon.lib /nologo /subsystem:console /machine:I386 /libpath:"..\..\Debug" 

CFLAGS_DEBUG   = /nologo /MDd /W4     /I "..\..\Common" /I "..\.." /I "..\..\Tests" /D "WIN32" /D "_DEBUG" /D "_CONSOLE" /D "_MBCS" /Fo"$(INTDIR_DEBUG)\\"   /c
CFLAGS_RELEASE = /nologo /MD  /W4 /O2 /I "..\..\Common" /I "..\.." /I "..\..\Tests" /D "WIN32" /D "NDEBUG" /D "_CONSOLE" /D "_MBCS" /Fo"$(INTDIR_RELEASE)\\" /c

OBJS_RELEASE= \
	"$(INTDIR_RELEASE)\genError.obj" \
	"$(INTDIR_RELEASE)\testParser.obj" 

OBJS_DEBUG = $(OBJS_RELEASE:.\Release\=.\Debug\)

###########################################################################
#
# Defines the rules.
#
###########################################################################

.c{$(INTDIR_RELEASE)}.obj::
	$(CPP) $(CFLAGS_RELEASE) $< 

.c{$(INTDIR_DEBUG)}.obj::
	$(CPP) $(CFLAGS_DEBUG) $< 

genError.c genError.h : testError.h
	..\Release\errorParser -i testError.h -o genError -p myErr

"$(OUTDIR_RELEASE)\testParser.exe" : "$(OUTDIR_RELEASE)" $(OBJS_RELEASE)
	$(LINK32) $(LDD_FLAGS_RELEASE) /OUT:"$(OUTDIR_RELEASE)\testParser.exe" $(OBJS_RELEASE)

"$(OUTDIR_DEBUG)\testParser.exe" : "$(OUTDIR_DEBUG)" $(OBJS_DEBUG)
	$(LINK32) $(LDD_FLAGS_DEBUG) /OUT:"$(OUTDIR_DEBUG)\testParser.exe" $(OBJS_DEBUG)

###########################################################################
#
# The targets
#
###########################################################################

check: $(OUTDIR_RELEASE) $(OUTDIR_RELEASE)\testParser.exe
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(OUTDIR_DEBUG)\testParser.exe
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

"$(OUTDIR_RELEASE)" :
	if not exist "$(OUTDIR_RELEASE)/$(NULL)" mkdir "$(OUTDIR_RELEASE)"

"$(OUTDIR_DEBUG)" :
	if not exist "$(OUTDIR_DEBUG)/$(NULL)" mkdir "$(OUTDIR_DEBUG)"
   
clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)
   -@erase genError.c genError.h

