# Copyright (C) 2008-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

check_PROGRAMS =                           \
        .\Release\Close.exe                \
        .\Release\Create.exe               \
        .\Release\CreateXML.exe            \
        .\Release\Delete.exe               \
        .\Release\Definition.exe           \
        .\Release\Edit.exe                 \
        .\Release\Empty.exe                \
        .\Release\FirstNullEntry.exe       \
        .\Release\FirstNullHandle.exe      \
        .\Release\FirstPass.exe            \
        .\Release\FirstWrongHandle.exe     \
        .\Release\Get.exe                  \
        .\Release\GetFirst.exe             \
        .\Release\GetNext.exe              \
        .\Release\Insert.exe               \
        .\Release\NextNoFirst.exe          \
        .\Release\NextNullEntry.exe        \
        .\Release\NextNullHandle.exe       \
        .\Release\NextPass.exe             \
        .\Release\NextWrongHandle.exe      \
        .\Release\OpenNoSession.exe        \
        .\Release\OpenPass.exe             \
        .\Release\Replace.exe              \
        .\Release\RetrieveNullEntry.exe    \
        .\Release\RetrieveNullHandle.exe   \
        .\Release\RetrieveNullKey.exe      \
        .\Release\RetrievePass.exe         \
        .\Release\RetrieveWrongHandle.exe  \
        .\Release\RetrieveZeroLength.exe   \
        .\Release\Status.exe               \
        .\Release\Tests.exe                

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

