# Copyright (C) 2006-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

check_PROGRAMS =                                 \
        .\Release\CommitEditNullContext.exe      \
        .\Release\CommitEditNullFolder.exe       \
        .\Release\CommitEditNullItem.exe         \
        .\Release\CommitEditNullMemObj.exe       \
        .\Release\CommitEditPass.exe             \
        .\Release\CommitEditWrongObjType.exe     \
        .\Release\CreateInvalidNameLength.exe    \
        .\Release\CreateNullContext.exe          \
        .\Release\CreateNullDefinition.exe       \
        .\Release\CreateNullFolder.exe           \
        .\Release\CreateNullName.exe             \
        .\Release\CreatePass.exe                 \
        .\Release\CreateWrongType.exe            \
        .\Release\DeleteNullContext.exe          \
        .\Release\DeleteNullFolder.exe           \
        .\Release\DeleteNullName.exe             \
        .\Release\DeletePass.exe                 \
        .\Release\DeleteWrongObjType.exe         \
        .\Release\DeleteZeroNameLength.exe       \
        .\Release\DestroyNullContext.exe         \
        .\Release\DestroyNullFolder.exe          \
        .\Release\DestroyNullName.exe            \
        .\Release\DestroyPass.exe                \
        .\Release\EditNullContext.exe            \
        .\Release\EditNullFolder.exe             \
        .\Release\EditNullItem.exe               \
        .\Release\EditNullName.exe               \
        .\Release\EditPass.exe                   \
        .\Release\EditWrongObjectType.exe        \
        .\Release\EditZeroNameLength.exe         \
        .\Release\FiniNullContext.exe            \
        .\Release\FiniNullFolder.exe             \
        .\Release\FiniPass.exe                   \
        .\Release\FiniWrongObjType.exe           \
        .\Release\GetFirstEmpty.exe              \
        .\Release\GetFirstNullContext.exe        \
        .\Release\GetFirstNullFolder.exe         \
        .\Release\GetFirstNullItem.exe           \
        .\Release\GetFirstPass.exe               \
        .\Release\GetFirstWrongObjType.exe       \
        .\Release\GetInvalidSig.exe              \
        .\Release\GetNextItemNullHashItem.exe    \
        .\Release\GetNextItemNullOffset.exe      \
        .\Release\GetNextNullContext.exe         \
        .\Release\GetNextNullFolder.exe          \
        .\Release\GetNextNullItem.exe            \
        .\Release\GetNextPass.exe                \
        .\Release\GetNextWrongObjType.exe        \
        .\Release\GetNullContext.exe             \
        .\Release\GetNullItem.exe                \
        .\Release\GetNullFolder.exe              \
        .\Release\GetNullName.exe                \
        .\Release\GetPass.exe                    \
        .\Release\GetStatusNullContext.exe       \
        .\Release\GetStatusNullFolder.exe        \
        .\Release\GetStatusNullName.exe          \
        .\Release\GetStatusNullStatus.exe        \
        .\Release\GetStatusPass.exe              \
        .\Release\GetStatusZeroLength.exe        \
        .\Release\GetWrongObjType.exe            \
        .\Release\GetZeroNameLength.exe          \
        .\Release\InitNullContext.exe            \
        .\Release\InitNullFolder.exe             \
        .\Release\InitNullHashItemOffset.exe     \
        .\Release\InitNullName.exe               \
        .\Release\InitNullParentOffset.exe       \
        .\Release\InitNullStatus.exe             \
        .\Release\InitPass.exe                   \
        .\Release\InitZeroBlocks.exe             \
        .\Release\InitZeroNameLength.exe         \
        .\Release\InsertNullContext.exe          \
        .\Release\InsertNullDefinition.exe       \
        .\Release\InsertNullFolder.exe           \
        .\Release\InsertNullName.exe             \
        .\Release\InsertNullOrigName.exe         \
        .\Release\InsertPass.exe                 \
        .\Release\InsertWrongObjType.exe         \
        .\Release\InsertZeroBlocks.exe           \
        .\Release\InsertZeroNameLength.exe       \
        .\Release\ReleaseNullContext.exe         \
        .\Release\ReleaseNullFolder.exe          \
        .\Release\ReleaseNullItem.exe            \
        .\Release\ReleasePass.exe                \
        .\Release\ReleaseWrongObjType.exe        \
        .\Release\RemoveNullContext.exe          \
        .\Release\RemoveNullFolder.exe           \
        .\Release\RemoveNullItem.exe             \
        .\Release\RemovePass.exe                 \
        .\Release\RemoveWrongObjType.exe         \
        .\Release\ResizeNullContext.exe          \
        .\Release\ResizeNullFolder.exe           \
        .\Release\ResizePass.exe                 \
        .\Release\StatusNullFolder.exe           \
        .\Release\StatusNullStatus.exe           \
        .\Release\StatusPass.exe                 \
        .\Release\Tests.exe                      \
        .\Release\TopCloseNullContext.exe        \
        .\Release\TopCloseNullItem.exe           \
        .\Release\TopClosePass.exe               \
        .\Release\TopCreateInvalidNameLength.exe \
        .\Release\TopCreateNullContext.exe       \
        .\Release\TopCreateNullDefinition.exe    \
        .\Release\TopCreateNullFolder.exe        \
        .\Release\TopCreateNullName.exe          \
        .\Release\TopCreatePass.exe              \
        .\Release\TopCreateWrongType.exe         \
        .\Release\TopDestroyNullContext.exe      \
        .\Release\TopDestroyNullFolder.exe       \
        .\Release\TopDestroyNullName.exe         \
        .\Release\TopDestroyPass.exe             \
        .\Release\TopEditNullContext.exe         \
        .\Release\TopEditNullFolder.exe          \
        .\Release\TopEditNullItem.exe            \
        .\Release\TopEditNullName.exe            \
        .\Release\TopEditPass.exe                \
        .\Release\TopEditWrongLength.exe         \
        .\Release\TopEditWrongType.exe           \
        .\Release\TopEditZeroLength.exe          \
        .\Release\TopOpenNullContext.exe         \
        .\Release\TopOpenNullItem.exe            \
        .\Release\TopOpenNullFolder.exe          \
        .\Release\TopOpenNullName.exe            \
        .\Release\TopOpenPass.exe                \
        .\Release\TopOpenWrongLength.exe         \
        .\Release\TopOpenWrongType.exe           \
        .\Release\TopOpenZeroLength.exe          \
        .\Release\TopStatusNullContext.exe       \
        .\Release\TopStatusNullFolder.exe        \
        .\Release\TopStatusNullName.exe          \
        .\Release\TopStatusNullStatus.exe        \
        .\Release\TopStatusPass.exe              \
        .\Release\ValidatePass.exe               

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

