# Copyright (C) 2006-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32.2005

RELEASE = Release2005
DEBUG = Debug2005

all: 

check_PROGRAMS =                               \
        .\$(RELEASE)\CommitEditNullContext.exe    \
        .\$(RELEASE)\CommitEditNullFolder.exe     \
        .\$(RELEASE)\CommitEditNullItem.exe       \
        .\$(RELEASE)\CommitEditNullMemObj.exe     \
        .\$(RELEASE)\CommitEditPass.exe           \
        .\$(RELEASE)\CommitEditWrongObjType.exe   \
        .\$(RELEASE)\CreateInvalidNameLength.exe  \
        .\$(RELEASE)\CreateNullContext.exe        \
        .\$(RELEASE)\CreateNullDefinition.exe     \
        .\$(RELEASE)\CreateNullFolder.exe         \
        .\$(RELEASE)\CreateNullName.exe           \
        .\$(RELEASE)\CreatePass.exe               \
        .\$(RELEASE)\CreateWrongType.exe          \
        .\$(RELEASE)\DeleteNullContext.exe        \
        .\$(RELEASE)\DeleteNullFolder.exe         \
        .\$(RELEASE)\DeleteNullName.exe           \
        .\$(RELEASE)\DeletePass.exe               \
        .\$(RELEASE)\DeleteWrongObjType.exe       \
        .\$(RELEASE)\DeleteZeroNameLength.exe     \
        .\$(RELEASE)\DestroyNullContext.exe       \
        .\$(RELEASE)\DestroyNullFolder.exe        \
        .\$(RELEASE)\DestroyNullName.exe          \
        .\$(RELEASE)\DestroyPass.exe              \
        .\$(RELEASE)\EditNullContext.exe          \
        .\$(RELEASE)\EditNullFolder.exe           \
        .\$(RELEASE)\EditNullItem.exe             \
        .\$(RELEASE)\EditNullName.exe             \
        .\$(RELEASE)\EditPass.exe                 \
        .\$(RELEASE)\EditWrongObjectType.exe      \
        .\$(RELEASE)\EditZeroNameLength.exe       \
        .\$(RELEASE)\FiniNullContext.exe          \
        .\$(RELEASE)\FiniNullFolder.exe           \
        .\$(RELEASE)\FiniPass.exe                 \
        .\$(RELEASE)\FiniWrongObjType.exe         \
        .\$(RELEASE)\GetDefinitionNullContext.exe \
        .\$(RELEASE)\GetDefinitionNullDataDef.exe \
        .\$(RELEASE)\GetDefinitionNullDef.exe     \
        .\$(RELEASE)\GetDefinitionNullFolder.exe  \
        .\$(RELEASE)\GetDefinitionNullKey.exe     \
        .\$(RELEASE)\GetDefinitionNullName.exe    \
        .\$(RELEASE)\GetDefinitionPass.exe        \
        .\$(RELEASE)\GetDefinitionZeroLength.exe  \
        .\$(RELEASE)\GetFirstEmpty.exe            \
        .\$(RELEASE)\GetFirstNullContext.exe      \
        .\$(RELEASE)\GetFirstNullFolder.exe       \
        .\$(RELEASE)\GetFirstNullItem.exe         \
        .\$(RELEASE)\GetFirstPass.exe             \
        .\$(RELEASE)\GetFirstWrongObjType.exe     \
        .\$(RELEASE)\GetInvalidSig.exe            \
        .\$(RELEASE)\GetNextItemNullHashItem.exe  \
        .\$(RELEASE)\GetNextItemNullOffset.exe    \
        .\$(RELEASE)\GetNextNullContext.exe       \
        .\$(RELEASE)\GetNextNullFolder.exe        \
        .\$(RELEASE)\GetNextNullItem.exe          \
        .\$(RELEASE)\GetNextPass.exe              \
        .\$(RELEASE)\GetNextWrongObjType.exe      \
        .\$(RELEASE)\GetNullContext.exe           \
        .\$(RELEASE)\GetNullItem.exe              \
        .\$(RELEASE)\GetNullFolder.exe            \
        .\$(RELEASE)\GetNullName.exe              \
        .\$(RELEASE)\GetPass.exe                  \
        .\$(RELEASE)\GetStatusNullContext.exe     \
        .\$(RELEASE)\GetStatusNullFolder.exe      \
        .\$(RELEASE)\GetStatusNullName.exe        \
        .\$(RELEASE)\GetStatusNullStatus.exe      \
        .\$(RELEASE)\GetStatusPass.exe            \
        .\$(RELEASE)\GetStatusZeroLength.exe      \
        .\$(RELEASE)\GetWrongObjType.exe          \
        .\$(RELEASE)\GetZeroNameLength.exe        \
        .\$(RELEASE)\InitNullContext.exe          \
        .\$(RELEASE)\InitNullFolder.exe           \
        .\$(RELEASE)\InitNullHashItemOffset.exe   \
        .\$(RELEASE)\InitNullName.exe             \
        .\$(RELEASE)\InitNullParentOffset.exe     \
        .\$(RELEASE)\InitNullStatus.exe           \
        .\$(RELEASE)\InitPass.exe                 \
        .\$(RELEASE)\InitZeroBlocks.exe           \
        .\$(RELEASE)\InitZeroNameLength.exe       \
        .\$(RELEASE)\InsertNullContext.exe        \
        .\$(RELEASE)\InsertNullDefinition.exe     \
        .\$(RELEASE)\InsertNullFolder.exe         \
        .\$(RELEASE)\InsertNullName.exe           \
        .\$(RELEASE)\InsertNullOrigName.exe       \
        .\$(RELEASE)\InsertPass.exe               \
        .\$(RELEASE)\InsertWrongObjType.exe       \
        .\$(RELEASE)\InsertZeroBlocks.exe         \
        .\$(RELEASE)\InsertZeroNameLength.exe     \
        .\$(RELEASE)\ReleaseNullContext.exe       \
        .\$(RELEASE)\ReleaseNullFolder.exe        \
        .\$(RELEASE)\ReleaseNullItem.exe          \
        .\$(RELEASE)\ReleasePass.exe              \
        .\$(RELEASE)\ReleaseWrongObjType.exe      \
        .\$(RELEASE)\RemoveNullContext.exe        \
        .\$(RELEASE)\RemoveNullFolder.exe         \
        .\$(RELEASE)\RemoveNullItem.exe           \
        .\$(RELEASE)\RemovePass.exe               \
        .\$(RELEASE)\RemoveWrongObjType.exe       \
        .\$(RELEASE)\ResizeNullContext.exe        \
        .\$(RELEASE)\ResizeNullFolder.exe         \
        .\$(RELEASE)\ResizePass.exe               \
        .\$(RELEASE)\RollbackEditNullContext.exe  \
        .\$(RELEASE)\RollbackEditNullFolder.exe   \
        .\$(RELEASE)\RollbackEditNullHashItem.exe \
        .\$(RELEASE)\RollbackEditPass.exe         \
        .\$(RELEASE)\RollbackEditWrongObjType.exe \
        .\$(RELEASE)\StatusNullFolder.exe         \
        .\$(RELEASE)\StatusNullStatus.exe         \
        .\$(RELEASE)\StatusPass.exe               \
        .\$(RELEASE)\Tests.exe                    \
        .\$(RELEASE)\ValidatePass.exe             

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(RELEASE) $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DEBUG)
	-@rmdir /Q $(DEBUG)
	-@erase /Q $(RELEASE)
	-@rmdir /Q $(RELEASE)
	-@erase /Q $(CLEANFILES)

