# Copyright (C) 2006 Daniel Prevost <dprevost@users.sourceforge.net>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

CLEANFILES = *~ 

check_PROGRAMS =                            \
                 .\Release\GetLongOptNullHandle.exe       \
                 .\Release\GetLongOptNullOpt.exe          \
                 .\Release\GetLongOptNullValue.exe        \
                 .\Release\GetLongOptPass.exe             \
                 .\Release\GetShortOptNullHandle.exe      \
                 .\Release\GetShortOptNullValue.exe       \
                 .\Release\GetShortOptPass.exe            \
                 .\Release\IsLongPresentNullHandle.exe    \
                 .\Release\IsLongPresentNullOpt.exe       \
                 .\Release\IsLongPresentPass.exe          \
                 .\Release\IsShortPresentNullHandle.exe   \
                 .\Release\IsShortPresentPass.exe         \
                 .\Release\SetOptionsNullHandle.exe       \
                 .\Release\SetOptionsNullOpts.exe         \
                 .\Release\SetOptionsNullEndedOpt.exe     \
                 .\Release\SetOptionsNullEndedComment.exe \
                 .\Release\SetOptionsNullEndedValue.exe   \
                 .\Release\SetOptionsNumOptsZero.exe      \
                 .\Release\SetOptionsPass.exe             \
                 .\Release\SetOptionsRepeatedLong.exe     \
                 .\Release\SetOptionsRepeatedShort.exe    \
                 .\Release\ShowUsageNullAddArgs.exe       \
                 .\Release\ShowUsageNullHandle.exe        \
                 .\Release\ShowUsageNullProgName.exe      \
                 .\Release\ShowUsagePass.exe              \
                 .\Release\Tests.exe                      \
                 .\Release\UnsetOptNullHandle.exe         \
                 .\Release\ValidateArgcZero.exe           \
                 .\Release\ValidateNullArgv.exe           \
                 .\Release\ValidateNULLArgvi.exe          \
                 .\Release\ValidateNullHandle.exe         \
                 .\Release\ValidatePass.exe               

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)
#

check: $(OUTDIR) $(check_PROGRAMS)
	python RunTests.py --path=Release

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	python RunTests.py --path=Debug

clean: 
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q $(CLEANFILES)

