# Copyright (C) 2006-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

RELEASE = Release2005
DEBUG = Debug2005
DLL_RELEASE = ..\..\..\Release2005
DLL_DEBUG = ..\..\..\Debug2005

all: 

CLEANFILES = *~ 

check_PROGRAMS =                                 \
        $(DIR_RELEASE)\GetLongOptNullHandle.exe       \
        $(DIR_RELEASE)\GetLongOptNullOpt.exe          \
        $(DIR_RELEASE)\GetLongOptNullValue.exe        \
        $(DIR_RELEASE)\GetLongOptPass.exe             \
        $(DIR_RELEASE)\GetShortOptNullHandle.exe      \
        $(DIR_RELEASE)\GetShortOptNullValue.exe       \
        $(DIR_RELEASE)\GetShortOptPass.exe            \
        $(DIR_RELEASE)\IsLongPresentNullHandle.exe    \
        $(DIR_RELEASE)\IsLongPresentNullOpt.exe       \
        $(DIR_RELEASE)\IsLongPresentPass.exe          \
        $(DIR_RELEASE)\IsShortPresentNullHandle.exe   \
        $(DIR_RELEASE)\IsShortPresentPass.exe         \
        $(DIR_RELEASE)\SetOptionsNullHandle.exe       \
        $(DIR_RELEASE)\SetOptionsNullOpts.exe         \
        $(DIR_RELEASE)\SetOptionsNullEndedOpt.exe     \
        $(DIR_RELEASE)\SetOptionsNullEndedComment.exe \
        $(DIR_RELEASE)\SetOptionsNullEndedValue.exe   \
        $(DIR_RELEASE)\SetOptionsNumOptsZero.exe      \
        $(DIR_RELEASE)\SetOptionsPass.exe             \
        $(DIR_RELEASE)\SetOptionsRepeatedLong.exe     \
        $(DIR_RELEASE)\SetOptionsRepeatedShort.exe    \
        $(DIR_RELEASE)\ShowUsageNullAddArgs.exe       \
        $(DIR_RELEASE)\ShowUsageNullHandle.exe        \
        $(DIR_RELEASE)\ShowUsageNullProgName.exe      \
        $(DIR_RELEASE)\ShowUsagePass.exe              \
        $(DIR_RELEASE)\Tests.exe                      \
        $(DIR_RELEASE)\UnsetOptNullHandle.exe         \
        $(DIR_RELEASE)\ValidateArgcZero.exe           \
        $(DIR_RELEASE)\ValidateNullArgv.exe           \
        $(DIR_RELEASE)\ValidateNULLArgvi.exe          \
        $(DIR_RELEASE)\ValidateNullHandle.exe         \
        $(DIR_RELEASE)\ValidatePass.exe               

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)\Tests
	-@rmdir /Q $(DIR_DEBUG)\Tests
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)\Tests
	-@rmdir /Q $(DIR_RELEASE)\Tests
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q ProjectFiles\*.dep
	-@erase /Q ProjectFiles\*.plg
	-@erase /Q ProjectFiles\*.mak
	-@erase /Q $(CLEANFILES)

