/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_info_2eproto__INCLUDED
#define PROTOBUF_C_info_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Pso__Info Pso__Info;


/* --- enums --- */


/* --- messages --- */

#include <photon/Photon/psoInfo.h>
typedef struct psoInfo _Pso__Info
#define PSO__INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pso__info__descriptor) \
    , 0, 0, 0, 0, 0,0, 0,0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL }


/* Pso__Info methods */
void   pso__info__init
                     (Pso__Info         *message);
size_t pso__info__get_packed_size
                     (const Pso__Info   *message);
size_t pso__info__pack
                     (const Pso__Info   *message,
                      uint8_t             *out);
size_t pso__info__pack_to_buffer
                     (const Pso__Info   *message,
                      ProtobufCBuffer     *buffer);
Pso__Info *
       pso__info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pso__info__free_unpacked
                     (Pso__Info *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Pso__Info_Closure)
                 (const Pso__Info *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pso__info__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_info_2eproto__INCLUDED */
