#! /usr/bin/env python
# encoding: utf-8
# :mode=python:  - For jedit

# Copyright (C) 2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

nucleus_list = [
        'psoErrorHandler.c',
        'BlockGroup.c',
        'Cursor.c',
        'FastMap.c',
        'Folder.c',
        'Hash.c',
        'HashTx.c',
        'hash_fnv.c',
        'HashMap.c',
        'InitEngine.c',
        'LinkedList.c',
        'LogFile.c',
        'MemBitmap.c',
        'MemoryAllocator.c',
        'MemoryObject.c',
        'Process.c',
        'ProcessManager.c',
        'Queue.c',
        'Session.c',
        'Set.c',
        'TopFolder.c',
        'Transaction.c']

def build(bld):
   print ' building in Common'
   nucleus_lib = bld.new_task_gen(
      features = 'cc cstaticlib',
      source = nucleus_list,
      includes='.. ../include',
      uselib_local   = 'Common',
      target='Nucleus')

   bld.add_subdirs(['Tests'])


