.TH "DataDefBuilderODBC" 3 "11 Apr 2009" "Version 0.5.0" "Photon C++ API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataDefBuilderODBC \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <photon/psoCommon.h>\fP
.br
\fC#include <photon/psoPhotonODBC.h>\fP
.br
\fC#include <photon/DataDefinition>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpso\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpso::DataDefBuilderODBC\fP"
.br
.RI "\fIThis class is a helper class to build the data definition of Photon objects when the definition is ODBC like. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photon C++ API from the source code.
