.TH "pso::DataDefinition" 3 "23 Apr 2009" "Version 0.5.0" "Photon C++ API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pso::DataDefinition \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This base class provides the 'interface' needed to both define and retrieve the definition of the fields of a data record. 
.PP
Definition at line 46 of file DataDefinition.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataDefinition\fP ()"
.br
.RI "\fIThis constructor does nothing. \fP"
.ti -1c
.RI "\fBDataDefinition\fP (Session &session, const std::string name, enum psoDefinitionType type, const unsigned char *dataDef, psoUint32 dataDefLength)"
.br
.RI "\fICreates a new data definition in shared memory. \fP"
.ti -1c
.RI "\fBDataDefinition\fP (Session &session, const std::string name)"
.br
.RI "\fIOpen an existing data definition in shared memory. \fP"
.ti -1c
.RI "virtual \fB~DataDefinition\fP ()"
.br
.RI "\fIThe destructor will close the definition if not closed. \fP"
.ti -1c
.RI "void \fBClose\fP ()"
.br
.RI "\fICloses the data definition. \fP"
.ti -1c
.RI "void \fBCreate\fP (Session &session, const std::string name, enum psoDefinitionType type, const unsigned char *dataDef, psoUint32 dataDefLength)"
.br
.RI "\fICreates a new data definition in shared memory. \fP"
.ti -1c
.RI "std::string \fBGetNext\fP ()"
.br
.RI "\fIIterates through the definition. \fP"
.ti -1c
.RI "void \fBGetDefinition\fP (unsigned char *buffer, psoUint32 bufferLength)"
.br
.RI "\fIRetrieves the data definition as an array of bytes. \fP"
.ti -1c
.RI "psoUint32 \fBGetLength\fP ()"
.br
.RI "\fIReturns the length, in bytes, of the definition. \fP"
.ti -1c
.RI "enum psoDefinitionType \fBGetType\fP ()"
.br
.RI "\fIReturns the type of the definition. \fP"
.ti -1c
.RI "void \fBOpen\fP (Session &session, const std::string name)"
.br
.RI "\fIOpen an existing data definition in shared memory. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBDataDefinition\fP (PSO_HANDLE sessionHandle, PSO_HANDLE definitionHandle)"
.br
.RI "\fIThis constructor is used by the other objects of this API to build the data definition. \fP"
.ti -1c
.RI "std::string \fBGetNextODBC\fP ()"
.br
.RI "\fIIterates through an ODBC definition. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "PSO_HANDLE \fBm_definitionHandle\fP"
.br
.ti -1c
.RI "PSO_HANDLE \fBm_sessionHandle\fP"
.br
.RI "\fIThe psoaSession struct (we belong to). \fP"
.ti -1c
.RI "enum psoDefinitionType \fBm_defType\fP"
.br
.ti -1c
.RI "const unsigned char * \fBm_dataDef\fP"
.br
.ti -1c
.RI "psoUint32 \fBm_dataDefLength\fP"
.br
.ti -1c
.RI "psoUint32 \fBm_currentLength\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBFastMap\fP"
.br
.ti -1c
.RI "class \fBFastMapEditor\fP"
.br
.ti -1c
.RI "class \fBFolder\fP"
.br
.ti -1c
.RI "class \fBHashMap\fP"
.br
.ti -1c
.RI "class \fBLifo\fP"
.br
.ti -1c
.RI "class \fBQueue\fP"
.br
.ti -1c
.RI "class \fBSession\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pso::DataDefinition::DataDefinition ()"
.PP
This constructor does nothing. 
.PP
You must use either Open or Create to use this object - otherwise a pso::Exception will be thrown. 
.SS "pso::DataDefinition::DataDefinition (Session & session, const std::string name, enum psoDefinitionType type, const unsigned char * dataDef, psoUint32 dataDefLength)"
.PP
Creates a new data definition in shared memory. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The session we belong to. 
.br
\fIname\fP The name of the definition. 
.br
\fItype\fP The type of definition (ODBC, user defined, etc.) 
.br
\fIdataDef\fP The data definition (as an opaque type) 
.br
\fIdataDefLength\fP The length in bytes of the buffer \fIdataDef\fP.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIpso::Exception\fP An abnormal error occured. 
.RE
.PP

.SS "pso::DataDefinition::DataDefinition (Session & session, const std::string name)"
.PP
Open an existing data definition in shared memory. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The session we belong to. 
.br
\fIname\fP The name of the definition.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIpso::Exception\fP An abnormal error occured. 
.RE
.PP

.SS "pso::DataDefinition::DataDefinition (PSO_HANDLE sessionHandle, PSO_HANDLE definitionHandle)\fC [private]\fP"
.PP
This constructor is used by the other objects of this API to build the data definition. 
.PP
\fBParameters:\fP
.RS 4
\fIsessionHandle\fP Handle to the session we belong to. 
.br
\fIdefinitionHandle\fP Handle to the definition
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIpso::Exception\fP An abnormal error occured. 
.RE
.PP

.SS "virtual pso::DataDefinition::~DataDefinition ()\fC [virtual]\fP"
.PP
The destructor will close the definition if not closed. 
.PP
This method won't throw an exception on error. 
.SH "Member Function Documentation"
.PP 
.SS "void pso::DataDefinition::Close ()"
.PP
Closes the data definition. 
.PP
This function terminates the current access to the data definition. The definition itself is left untouched in shared memory.
.PP
\fBExceptions:\fP
.RS 4
\fIpso::Exception\fP An abnormal error occured. 
.RE
.PP

.SS "void pso::DataDefinition::Create (Session & session, const std::string name, enum psoDefinitionType type, const unsigned char * dataDef, psoUint32 dataDefLength)"
.PP
Creates a new data definition in shared memory. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The session we belong to. 
.br
\fIname\fP The name of the definition. 
.br
\fItype\fP The type of definition (ODBC, user defined, etc.) 
.br
\fIdataDef\fP The data definition (as an opaque type) 
.br
\fIdataDefLength\fP The length in bytes of the buffer \fIdataDef\fP.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIpso::Exception\fP An abnormal error occured. 
.RE
.PP

.SS "std::string pso::DataDefinition::GetNext ()"
.PP
Iterates through the definition. 
.PP
\fBReturns:\fP
.RS 4
A formatted string containing the information on an item of the definition.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIpso::Exception\fP An abnormal error occured. 
.RE
.PP

.SS "void pso::DataDefinition::GetDefinition (unsigned char * buffer, psoUint32 bufferLength)"
.PP
Retrieves the data definition as an array of bytes. 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP A buffer to copy the data definition. 
.br
\fIbufferLength\fP The length in bytes of \fIbuffer\fP.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIpso::Exception\fP An abnormal error occured. 
.RE
.PP

.SS "psoUint32 pso::DataDefinition::GetLength ()"
.PP
Returns the length, in bytes, of the definition. 
.PP
This function can be used to determine the length of the buffer that must be allocated for GetDefinition().
.PP
\fBReturns:\fP
.RS 4
The length, in bytes, of the definition
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIpso::Exception\fP An abnormal error occured. 
.RE
.PP

.SS "enum psoDefinitionType pso::DataDefinition::GetType ()"
.PP
Returns the type of the definition. 
.PP
\fBReturns:\fP
.RS 4
The type of the definition.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIpso::Exception\fP An abnormal error occured. 
.RE
.PP

.SS "void pso::DataDefinition::Open (Session & session, const std::string name)"
.PP
Open an existing data definition in shared memory. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The session we belong to. 
.br
\fIname\fP The name of the definition.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIpso::Exception\fP An abnormal error occured. 
.RE
.PP

.SS "std::string pso::DataDefinition::GetNextODBC ()\fC [private]\fP"
.PP
Iterates through an ODBC definition. 
.PP
\fBReturns:\fP
.RS 4
A formatted string containing the information on an item of the definition.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIpso::Exception\fP An abnormal error occured. 
.RE
.PP

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class FastMap\fC [friend]\fP"
.PP
Definition at line 198 of file DataDefinition.
.SS "friend class FastMapEditor\fC [friend]\fP"
.PP
Definition at line 199 of file DataDefinition.
.SS "friend class Folder\fC [friend]\fP"
.PP
Definition at line 200 of file DataDefinition.
.SS "friend class HashMap\fC [friend]\fP"
.PP
Definition at line 201 of file DataDefinition.
.SS "friend class Lifo\fC [friend]\fP"
.PP
Definition at line 202 of file DataDefinition.
.SS "friend class Queue\fC [friend]\fP"
.PP
Definition at line 203 of file DataDefinition.
.SS "friend class Session\fC [friend]\fP"
.PP
Definition at line 204 of file DataDefinition.
.SH "Member Data Documentation"
.PP 
.SS "PSO_HANDLE \fBpso::DataDefinition::m_definitionHandle\fP\fC [private]\fP"
.PP
Definition at line 188 of file DataDefinition.
.SS "PSO_HANDLE \fBpso::DataDefinition::m_sessionHandle\fP\fC [private]\fP"
.PP
The psoaSession struct (we belong to). 
.PP
Definition at line 191 of file DataDefinition.
.SS "enum psoDefinitionType \fBpso::DataDefinition::m_defType\fP\fC [private]\fP"
.PP
Definition at line 193 of file DataDefinition.
.SS "const unsigned char* \fBpso::DataDefinition::m_dataDef\fP\fC [private]\fP"
.PP
Definition at line 194 of file DataDefinition.
.SS "psoUint32 \fBpso::DataDefinition::m_dataDefLength\fP\fC [private]\fP"
.PP
Definition at line 195 of file DataDefinition.
.SS "psoUint32 \fBpso::DataDefinition::m_currentLength\fP\fC [private]\fP"
.PP
Definition at line 196 of file DataDefinition.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon C++ API from the source code.
