.TH "psoFolderEntry" 3 "26 Aug 2008" "Version 0.3.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoFolderEntry \- 
.SH SYNOPSIS
.br
.PP
\fC#include <psoCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
This data structure is used to iterate throught all objects in a folder. 

Note: the actual name of an object (and the length of this name) might vary if you are using different locales (internally, names are stored as wide characters (4 bytes)). 
.PP
Definition at line 206 of file psoCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpsoObjectType\fP \fBtype\fP"
.br
.RI "\fIThe object type. \fP"
.ti -1c
.RI "int \fBstatus\fP"
.br
.RI "\fIStatus (created but not committed, etc. \fP"
.ti -1c
.RI "size_t \fBnameLengthInBytes\fP"
.br
.RI "\fIThe actual length of the name of the object. \fP"
.ti -1c
.RI "char \fBname\fP [PSO_MAX_NAME_LENGTH]"
.br
.RI "\fIThe name of the object. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBpsoObjectType\fP \fBpsoFolderEntry::type\fP"
.PP
The object type. 
.PP
Definition at line 209 of file psoCommon.h.
.SS "int \fBpsoFolderEntry::status\fP"
.PP
Status (created but not committed, etc. 
.PP
) - not used in version 0.1 
.PP
Definition at line 212 of file psoCommon.h.
.SS "size_t \fBpsoFolderEntry::nameLengthInBytes\fP"
.PP
The actual length of the name of the object. 
.PP
Definition at line 215 of file psoCommon.h.
.SS "char \fBpsoFolderEntry::name\fP[PSO_MAX_NAME_LENGTH]"
.PP
The name of the object. 
.PP
Definition at line 218 of file psoCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
