.TH "psoFolderEntry" 3 "12 Dec 2008" "Version 0.4.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoFolderEntry \- 
.SH SYNOPSIS
.br
.PP
\fC#include <psoCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
This data structure is used to iterate throught all objects in a folder. 
.PP
Definition at line 252 of file psoCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [PSO_MAX_NAME_LENGTH]"
.br
.RI "\fIThe name of the object. \fP"
.ti -1c
.RI "\fBpsoObjectType\fP \fBtype\fP"
.br
.RI "\fIThe object type. \fP"
.ti -1c
.RI "int \fBstatus\fP"
.br
.RI "\fIStatus of the object. \fP"
.ti -1c
.RI "\fBpsoUint32\fP \fBnameLengthInBytes\fP"
.br
.RI "\fIThe actual length (in bytes) of the name of the object. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "char \fBpsoFolderEntry::name\fP[PSO_MAX_NAME_LENGTH]"
.PP
The name of the object. 
.PP

.PP
Definition at line 255 of file psoCommon.h.
.SS "\fBpsoObjectType\fP \fBpsoFolderEntry::type\fP"
.PP
The object type. 
.PP
Definition at line 258 of file psoCommon.h.
.SS "int \fBpsoFolderEntry::status\fP"
.PP
Status of the object. 
.PP
For example, created but not committed, etc. 
.PP
Definition at line 265 of file psoCommon.h.
.SS "\fBpsoUint32\fP \fBpsoFolderEntry::nameLengthInBytes\fP"
.PP
The actual length (in bytes) of the name of the object. 
.PP

.PP
Definition at line 268 of file psoCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
