.TH "psoHashMap.h" 3 "26 Aug 2008" "Version 0.3.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoHashMap.h \- 
.SH "Detailed Description"
.PP 
This file provides the API needed to access a Photon hash map. 

Hash maps use unique keys - the data items are not sorted. 
.PP
Definition in file \fBpsoHashMap.h\fP.
.SH SYNOPSIS
.br
.PP
\fC#include <photon/psoCommon.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "PHOTON_EXPORT int \fBpsoHashMapClose\fP (\fBPSO_HANDLE\fP objectHandle)"
.br
.RI "\fIClose a Hash Map. \fP"
.ti -1c
.RI "PHOTON_EXPORT int \fBpsoHashMapDefinition\fP (\fBPSO_HANDLE\fP objectHandle, \fBpsoObjectDefinition\fP **definition)"
.br
.RI "\fIRetrieve the data definition of the hash map. \fP"
.ti -1c
.RI "PHOTON_EXPORT int \fBpsoHashMapDelete\fP (\fBPSO_HANDLE\fP objectHandle, const void *key, size_t keyLength)"
.br
.RI "\fIRemove the data item identified by the given key from the hash map. \fP"
.ti -1c
.RI "PHOTON_EXPORT int \fBpsoHashMapGet\fP (\fBPSO_HANDLE\fP objectHandle, const void *key, size_t keyLength, void *buffer, size_t bufferLength, size_t *returnedLength)"
.br
.RI "\fIRetrieve the data item identified by the given key from the hash map. \fP"
.ti -1c
.RI "PHOTON_EXPORT int \fBpsoHashMapGetFirst\fP (\fBPSO_HANDLE\fP objectHandle, void *key, size_t keyLength, void *buffer, size_t bufferLength, size_t *retKeyLength, size_t *retDataLength)"
.br
.RI "\fIIterate through the hash map. \fP"
.ti -1c
.RI "PHOTON_EXPORT int \fBpsoHashMapGetNext\fP (\fBPSO_HANDLE\fP objectHandle, void *key, size_t keyLength, void *buffer, size_t bufferLength, size_t *retKeyLength, size_t *retDataLength)"
.br
.RI "\fIIterate through the hash map. \fP"
.ti -1c
.RI "PHOTON_EXPORT int \fBpsoHashMapInsert\fP (\fBPSO_HANDLE\fP objectHandle, const void *key, size_t keyLength, const void *data, size_t dataLength)"
.br
.RI "\fIInsert a data element in the hash map. \fP"
.ti -1c
.RI "PHOTON_EXPORT int \fBpsoHashMapOpen\fP (\fBPSO_HANDLE\fP sessionHandle, const char *hashMapName, size_t nameLengthInBytes, \fBPSO_HANDLE\fP *objectHandle)"
.br
.RI "\fIOpen an existing hash map (see \fBpsoCreateObject\fP to create a new object). \fP"
.ti -1c
.RI "PHOTON_EXPORT int \fBpsoHashMapReplace\fP (\fBPSO_HANDLE\fP objectHandle, const void *key, size_t keyLength, const void *data, size_t dataLength)"
.br
.RI "\fIReplace a data element in the hash map. \fP"
.ti -1c
.RI "PHOTON_EXPORT int \fBpsoHashMapStatus\fP (\fBPSO_HANDLE\fP objectHandle, \fBpsoObjStatus\fP *pStatus)"
.br
.RI "\fIReturn the status of the hash map. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
