.TH "psoInfo" 3 "11 Dec 2008" "Version 0.4.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoInfo \- 
.SH SYNOPSIS
.br
.PP
\fC#include <psoCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
This data structure is used to retrieve the status of the Photon shared memory. 
.PP
Definition at line 318 of file psoCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBtotalSizeInBytes\fP"
.br
.RI "\fITotal size of the virtual data space. \fP"
.ti -1c
.RI "size_t \fBallocatedSizeInBytes\fP"
.br
.RI "\fITotal size of the allocated blocks. \fP"
.ti -1c
.RI "size_t \fBnumObjects\fP"
.br
.RI "\fINumber of API objects in the pso (internal objects are not counted). \fP"
.ti -1c
.RI "size_t \fBnumGroups\fP"
.br
.RI "\fITotal number of groups of blocks. \fP"
.ti -1c
.RI "size_t \fBnumMallocs\fP"
.br
.RI "\fINumber of calls to allocate groups of blocks. \fP"
.ti -1c
.RI "size_t \fBnumFrees\fP"
.br
.RI "\fINumber of calls to free groups of blocks. \fP"
.ti -1c
.RI "size_t \fBlargestFreeInBytes\fP"
.br
.RI "\fILargest contiguous group of free blocks. \fP"
.ti -1c
.RI "int \fBmemoryVersion\fP"
.br
.RI "\fIShared-memory version. \fP"
.ti -1c
.RI "int \fBbigEndian\fP"
.br
.RI "\fIEndianess (0 for little endian, 1 for big endian). \fP"
.ti -1c
.RI "char \fBcompiler\fP [20]"
.br
.RI "\fICompiler name. \fP"
.ti -1c
.RI "char \fBcompilerVersion\fP [10]"
.br
.RI "\fICompiler version (if available). \fP"
.ti -1c
.RI "char \fBplatform\fP [20]"
.br
.RI "\fIPlatform. \fP"
.ti -1c
.RI "char \fBdllVersion\fP [10]"
.br
.RI "\fIShared lib version. \fP"
.ti -1c
.RI "char \fBquasarVersion\fP [10]"
.br
.RI "\fIThe server version (of the pso creator). \fP"
.ti -1c
.RI "char \fBcreationTime\fP [30]"
.br
.RI "\fITimestamp of creation of the shared memory. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t \fBpsoInfo::totalSizeInBytes\fP"
.PP
Total size of the virtual data space. 
.PP

.PP
Definition at line 321 of file psoCommon.h.
.SS "size_t \fBpsoInfo::allocatedSizeInBytes\fP"
.PP
Total size of the allocated blocks. 
.PP

.PP
Definition at line 324 of file psoCommon.h.
.SS "size_t \fBpsoInfo::numObjects\fP"
.PP
Number of API objects in the pso (internal objects are not counted). 
.PP

.PP
Definition at line 327 of file psoCommon.h.
.SS "size_t \fBpsoInfo::numGroups\fP"
.PP
Total number of groups of blocks. 
.PP

.PP
Definition at line 330 of file psoCommon.h.
.SS "size_t \fBpsoInfo::numMallocs\fP"
.PP
Number of calls to allocate groups of blocks. 
.PP

.PP
Definition at line 333 of file psoCommon.h.
.SS "size_t \fBpsoInfo::numFrees\fP"
.PP
Number of calls to free groups of blocks. 
.PP

.PP
Definition at line 336 of file psoCommon.h.
.SS "size_t \fBpsoInfo::largestFreeInBytes\fP"
.PP
Largest contiguous group of free blocks. 
.PP

.PP
Definition at line 339 of file psoCommon.h.
.SS "int \fBpsoInfo::memoryVersion\fP"
.PP
Shared-memory version. 
.PP

.PP
Definition at line 342 of file psoCommon.h.
.SS "int \fBpsoInfo::bigEndian\fP"
.PP
Endianess (0 for little endian, 1 for big endian). 
.PP

.PP
Definition at line 345 of file psoCommon.h.
.SS "char \fBpsoInfo::compiler\fP[20]"
.PP
Compiler name. 
.PP

.PP
Definition at line 348 of file psoCommon.h.
.SS "char \fBpsoInfo::compilerVersion\fP[10]"
.PP
Compiler version (if available). 
.PP

.PP
Definition at line 351 of file psoCommon.h.
.SS "char \fBpsoInfo::platform\fP[20]"
.PP
Platform. 
.PP

.PP
Definition at line 354 of file psoCommon.h.
.SS "char \fBpsoInfo::dllVersion\fP[10]"
.PP
Shared lib version. 
.PP

.PP
Definition at line 357 of file psoCommon.h.
.SS "char \fBpsoInfo::quasarVersion\fP[10]"
.PP
The server version (of the pso creator). 
.PP

.PP
Definition at line 360 of file psoCommon.h.
.SS "char \fBpsoInfo::creationTime\fP[30]"
.PP
Timestamp of creation of the shared memory. 
.PP

.PP
Definition at line 363 of file psoCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
