.TH "psoKeyDefinition" 3 "27 Jan 2009" "Version 0.5.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoKeyDefinition \- 
.SH SYNOPSIS
.br
.PP
\fC#include <psoCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
Description of the structure of the hash map key. 
.PP
Definition at line 167 of file psoCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBpsoKeyType\fP \fBtype\fP"
.br
.RI "\fIThe data type of the key. \fP"
.ti -1c
.RI "\fBpsoUint32\fP \fBlength\fP"
.br
.RI "\fIFor fixed-length data types. \fP"
.ti -1c
.RI "\fBpsoUint32\fP \fBminLength\fP"
.br
.RI "\fIFor variable-length data types. \fP"
.ti -1c
.RI "\fBpsoUint32\fP \fBmaxLength\fP"
.br
.RI "\fIFor variable-length data types. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "enum \fBpsoKeyType\fP \fBpsoKeyDefinition::type\fP"
.PP
The data type of the key. 
.PP

.PP
Definition at line 170 of file psoCommon.h.
.SS "\fBpsoUint32\fP \fBpsoKeyDefinition::length\fP"
.PP
For fixed-length data types. 
.PP
Definition at line 173 of file psoCommon.h.
.SS "\fBpsoUint32\fP \fBpsoKeyDefinition::minLength\fP"
.PP
For variable-length data types. 
.PP
Definition at line 176 of file psoCommon.h.
.SS "\fBpsoUint32\fP \fBpsoKeyDefinition::maxLength\fP"
.PP
For variable-length data types. 
.PP
Definition at line 179 of file psoCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
