.TH "psoKeyFieldDefinition" 3 "25 Jun 2009" "Version 0.5.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoKeyFieldDefinition \- 
.SH SYNOPSIS
.br
.PP
\fC#include <psoPhotonODBC.h>\fP
.PP
.SH "Detailed Description"
.PP 
Description of the structure of the hash map key. 
.PP
Definition at line 145 of file psoPhotonODBC.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [PSO_MAX_FIELD_LENGTH]"
.br
.RI "\fIThe name of a field of the key. \fP"
.ti -1c
.RI "enum \fBpsoKeyType\fP \fBtype\fP"
.br
.RI "\fIThe data type of the key. \fP"
.ti -1c
.RI "\fBpsoUint32\fP \fBlength\fP"
.br
.RI "\fIFor some of the fixed and variable-length data types. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "char \fBpsoKeyFieldDefinition::name\fP[PSO_MAX_FIELD_LENGTH]"
.PP
The name of a field of the key. 
.PP

.PP
Definition at line 148 of file psoPhotonODBC.h.
.SS "enum \fBpsoKeyType\fP \fBpsoKeyFieldDefinition::type\fP"
.PP
The data type of the key. 
.PP

.PP
Definition at line 151 of file psoPhotonODBC.h.
.SS "\fBpsoUint32\fP \fBpsoKeyFieldDefinition::length\fP"
.PP
For some of the fixed and variable-length data types. 
.PP
Definition at line 154 of file psoPhotonODBC.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
