.TH "psoKeyDefinition" 3 "12 Oct 2008" "Version 0.3.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoKeyDefinition \- 
.SH SYNOPSIS
.br
.PP
\fC#include <psoCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
Description of the structure of the hash map key. 
.PP
Definition at line 152 of file psoCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBpsoKeyType\fP \fBtype\fP"
.br
.RI "\fIThe data type of the key. \fP"
.ti -1c
.RI "size_t \fBlength\fP"
.br
.RI "\fIFor fixed-length data types. \fP"
.ti -1c
.RI "size_t \fBminLength\fP"
.br
.RI "\fIFor variable-length data types. \fP"
.ti -1c
.RI "size_t \fBmaxLength\fP"
.br
.RI "\fIFor variable-length data types. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "enum \fBpsoKeyType\fP \fBpsoKeyDefinition::type\fP"
.PP
The data type of the key. 
.PP

.PP
Definition at line 155 of file psoCommon.h.
.SS "size_t \fBpsoKeyDefinition::length\fP"
.PP
For fixed-length data types. 
.PP
Definition at line 158 of file psoCommon.h.
.SS "size_t \fBpsoKeyDefinition::minLength\fP"
.PP
For variable-length data types. 
.PP
Definition at line 161 of file psoCommon.h.
.SS "size_t \fBpsoKeyDefinition::maxLength\fP"
.PP
For variable-length data types. 
.PP
Definition at line 164 of file psoCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
