.TH "psoKeyDefinition" 3 "10 Oct 2008" "Version 0.3.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoKeyDefinition \- 
.SH SYNOPSIS
.br
.PP
\fC#include <psoCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
Description of the structure of the hash map key. 
.PP
Definition at line 145 of file psoCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBpsoKeyType\fP \fBtype\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.ti -1c
.RI "size_t \fBminLength\fP"
.br
.ti -1c
.RI "size_t \fBmaxLength\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "enum \fBpsoKeyType\fP \fBpsoKeyDefinition::type\fP"
.PP
Definition at line 147 of file psoCommon.h.
.SS "size_t \fBpsoKeyDefinition::length\fP"
.PP
Definition at line 148 of file psoCommon.h.
.SS "size_t \fBpsoKeyDefinition::minLength\fP"
.PP
Definition at line 149 of file psoCommon.h.
.SS "size_t \fBpsoKeyDefinition::maxLength\fP"
.PP
Definition at line 150 of file psoCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
