.TH "psoNumericStruct" 3 "28 Feb 2009" "Version 0.5.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoNumericStruct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <psoPhotonODBC.h>\fP
.PP
.SH "Detailed Description"
.PP 
Definition at line 213 of file psoPhotonODBC.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBprecision\fP"
.br
.ti -1c
.RI "signed char \fBscale\fP"
.br
.ti -1c
.RI "unsigned char \fBsign\fP"
.br
.ti -1c
.RI "unsigned char \fBval\fP [PSO_MAX_NUMERIC_LEN]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char \fBpsoNumericStruct::precision\fP"
.PP
Definition at line 214 of file psoPhotonODBC.h.
.SS "signed char \fBpsoNumericStruct::scale\fP"
.PP
Definition at line 215 of file psoPhotonODBC.h.
.SS "unsigned char \fBpsoNumericStruct::sign\fP"
.PP
Definition at line 216 of file psoPhotonODBC.h.
.SS "unsigned char \fBpsoNumericStruct::val\fP[PSO_MAX_NUMERIC_LEN]"
.PP
Definition at line 217 of file psoPhotonODBC.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
