.TH "psoObjectDefinition" 3 "27 Mar 2009" "Version 0.5.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoObjectDefinition \- 
.SH SYNOPSIS
.br
.PP
\fC#include <psoCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
This struct contains the basic elements defining an object (type, number of fields, etc). 

This struct will be expanded in the near future to add hints to the framework for better utilization of resources (cpu, RAM).
.PP
For exmple: the expected minimal number of data records can be used to preallocate the internal hash array (avoiding unneeded Resize() and potential memory fragmentation). 
.PP
Definition at line 170 of file psoCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBpsoObjectType\fP \fBtype\fP"
.br
.RI "\fIThe object type. \fP"
.ti -1c
.RI "enum \fBpsoDefinitionType\fP \fBkeyDefType\fP"
.br
.RI "\fIThe type of the key definition (metadata). \fP"
.ti -1c
.RI "enum \fBpsoDefinitionType\fP \fBfieldDefType\fP"
.br
.RI "\fIThe type of the field definition (metadata). \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "enum \fBpsoObjectType\fP \fBpsoObjectDefinition::type\fP"
.PP
The object type. 
.PP

.PP
Definition at line 173 of file psoCommon.h.
.SS "enum \fBpsoDefinitionType\fP \fBpsoObjectDefinition::keyDefType\fP"
.PP
The type of the key definition (metadata). 
.PP
Definition at line 176 of file psoCommon.h.
.SS "enum \fBpsoDefinitionType\fP \fBpsoObjectDefinition::fieldDefType\fP"
.PP
The type of the field definition (metadata). 
.PP
Definition at line 179 of file psoCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
