.TH "psoObjectDefinition" 3 "11 Dec 2008" "Version 0.4.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoObjectDefinition \- 
.SH SYNOPSIS
.br
.PP
\fC#include <psoCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
This struct has a variable length. 
.PP
Definition at line 222 of file psoCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBpsoObjectType\fP \fBtype\fP"
.br
.RI "\fIThe object type. \fP"
.ti -1c
.RI "\fBpsoUint32\fP \fBnumFields\fP"
.br
.RI "\fIThe number of fields in the definition. \fP"
.ti -1c
.RI "\fBpsoKeyDefinition\fP \fBkey\fP"
.br
.RI "\fIThe data definition of the key (hash map/fast map only). \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "enum \fBpsoObjectType\fP \fBpsoObjectDefinition::type\fP"
.PP
The object type. 
.PP

.PP
Definition at line 225 of file psoCommon.h.
.SS "\fBpsoUint32\fP \fBpsoObjectDefinition::numFields\fP"
.PP
The number of fields in the definition. 
.PP

.PP
Definition at line 228 of file psoCommon.h.
.SS "\fBpsoKeyDefinition\fP \fBpsoObjectDefinition::key\fP"
.PP
The data definition of the key (hash map/fast map only). 
.PP
Definition at line 231 of file psoCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
