.TH "API functions for Photon processes." 3 "23 Apr 2009" "Version 0.5.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
API functions for Photon processes. \- 
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "PHOTON_EXPORT void \fBpsoExit\fP (void)"
.br
.RI "\fIThis function terminates all access to shared memory. \fP"
.ti -1c
.RI "PHOTON_EXPORT int \fBpsoInit\fP (const char *quasarAddress)"
.br
.RI "\fIThis function initializes access to the shared-memory of Photon. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "PHOTON_EXPORT void psoExit (void)"
.PP
This function terminates all access to shared memory. 
.PP
This function will also close all sessions and terminate all accesses to the different objects.
.PP
This function takes no argument and always end successfully (even if called twice or if \fBpsoInit\fP was not called). 
.SS "PHOTON_EXPORT int psoInit (const char * quasarAddress)"
.PP
This function initializes access to the shared-memory of Photon. 
.PP
It takes a single input argument, the address of Quasar, the Photon server or the name of the shared-memory file.
.PP
\fBParameters:\fP
.RS 4
\fIquasarAddress\fP The address of Quasar, currently a string with the port number ('12345'). It can also be the name of the shared-memory file - in this case add the prefix 'file:' to the name.
.RE
.PP
\fBReturns:\fP
.RS 4
0 on success or a \fBpsoErrors\fP on error. 
.RE
.PP

