.TH "psoProcess.h" 3 "24 Aug 2008" "Version 0.3.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoProcess.h \- 
.SH "Detailed Description"
.PP 
This file provides the API functions for psof processes. 


.PP
Definition in file \fBpsoProcess.h\fP.
.SH SYNOPSIS
.br
.PP
\fC#include <photon/psoCommon.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "VDSF_EXPORT void \fBpsoExit\fP ()"
.br
.RI "\fIThis function terminates all access to the VDS. \fP"
.ti -1c
.RI "VDSF_EXPORT int \fBpsoInit\fP (const char *wdAddress, int protectionNeeded)"
.br
.RI "\fIThis function initializes access to a VDS. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
