.TH "psoQueue" 3 "6 Dec 2008" "Version 0.4.0" "Photon C++ API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoQueue \- 
.SH SYNOPSIS
.br
.PP
\fC#include <photon/psoCommon.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpso\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpso::Queue\fP"
.br
.RI "\fIPhoton FIFO queues (First In, First Out). \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photon C++ API from the source code.
