.TH "psoTimeStampStruct" 3 "23 Apr 2009" "Version 0.5.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoTimeStampStruct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <psoPhotonODBC.h>\fP
.PP
.SH "Detailed Description"
.PP 
Definition at line 209 of file psoPhotonODBC.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpsoInt16\fP \fByear\fP"
.br
.ti -1c
.RI "\fBpsoUint16\fP \fBmonth\fP"
.br
.ti -1c
.RI "\fBpsoUint16\fP \fBday\fP"
.br
.ti -1c
.RI "\fBpsoUint16\fP \fBhour\fP"
.br
.ti -1c
.RI "\fBpsoUint16\fP \fBminute\fP"
.br
.ti -1c
.RI "\fBpsoUint16\fP \fBsecond\fP"
.br
.ti -1c
.RI "\fBpsoUint32\fP \fBfraction\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBpsoInt16\fP \fBpsoTimeStampStruct::year\fP"
.PP
Definition at line 210 of file psoPhotonODBC.h.
.SS "\fBpsoUint16\fP \fBpsoTimeStampStruct::month\fP"
.PP
Definition at line 211 of file psoPhotonODBC.h.
.SS "\fBpsoUint16\fP \fBpsoTimeStampStruct::day\fP"
.PP
Definition at line 212 of file psoPhotonODBC.h.
.SS "\fBpsoUint16\fP \fBpsoTimeStampStruct::hour\fP"
.PP
Definition at line 213 of file psoPhotonODBC.h.
.SS "\fBpsoUint16\fP \fBpsoTimeStampStruct::minute\fP"
.PP
Definition at line 214 of file psoPhotonODBC.h.
.SS "\fBpsoUint16\fP \fBpsoTimeStampStruct::second\fP"
.PP
Definition at line 215 of file psoPhotonODBC.h.
.SS "\fBpsoUint32\fP \fBpsoTimeStampStruct::fraction\fP"
.PP
Definition at line 216 of file psoPhotonODBC.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
