.TH "psoTimeStruct" 3 "25 Jun 2009" "Version 0.5.0" "Photon Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoTimeStruct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <psoPhotonODBC.h>\fP
.PP
.SH "Detailed Description"
.PP 
Definition at line 203 of file psoPhotonODBC.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpsoUint16\fP \fBhour\fP"
.br
.ti -1c
.RI "\fBpsoUint16\fP \fBminute\fP"
.br
.ti -1c
.RI "\fBpsoUint16\fP \fBsecond\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBpsoUint16\fP \fBpsoTimeStruct::hour\fP"
.PP
Definition at line 204 of file psoPhotonODBC.h.
.SS "\fBpsoUint16\fP \fBpsoTimeStruct::minute\fP"
.PP
Definition at line 205 of file psoPhotonODBC.h.
.SS "\fBpsoUint16\fP \fBpsoTimeStruct::second\fP"
.PP
Definition at line 206 of file psoPhotonODBC.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photon Software from the source code.
