.TH "vdsFolderEntry" 3 "21 Oct 2007" "Version 0.1" "vdsf C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vdsFolderEntry \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vdsCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
Definition at line 96 of file vdsCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBvdsObjectType\fP \fBtype\fP"
.br
.ti -1c
.RI "size_t \fBnameLengthInBytes\fP"
.br
.ti -1c
.RI "char \fBname\fP [VDS_MAX_NAME_LENGTH *4]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBvdsObjectType\fP \fBvdsFolderEntry::type\fP"
.PP
Definition at line 98 of file vdsCommon.h.
.SS "size_t \fBvdsFolderEntry::nameLengthInBytes\fP"
.PP
Definition at line 100 of file vdsCommon.h.
.SS "char \fBvdsFolderEntry::name\fP[VDS_MAX_NAME_LENGTH *4]"
.PP
Definition at line 102 of file vdsCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for vdsf C API from the source code.
