.TH "vdsFolder" 3 "4 Nov 2006" "Version 0.1" "vdsf C++ API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vdsFolder \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vdsFolder.h>\fP
.PP
.SH "Detailed Description"
.PP 
Definition at line 31 of file vdsFolder.h.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvdsFolder\fP (vdsSession &session)"
.br
.ti -1c
.RI "virtual \fB~vdsFolder\fP ()"
.br
.ti -1c
.RI "int \fBOpen\fP (const char *folderName)"
.br
.ti -1c
.RI "int \fBClose\fP ()"
.br
.ti -1c
.RI "int \fBGetFirstItem\fP (vdsFolderItem *pFolderItem)"
.br
.ti -1c
.RI "int \fBGetNextItem\fP (vdsFolderItem *pFolderItem)"
.br
.ti -1c
.RI "int \fBRemoveAll\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "vdsProxyObject * \fBm_pProxyObject\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vdsFolder::vdsFolder (vdsSession & session)"
.PP
.SS "virtual vdsFolder::~vdsFolder ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "int vdsFolder::Close ()"
.PP
.SS "int vdsFolder::GetFirstItem (vdsFolderItem * pFolderItem)"
.PP
.SS "int vdsFolder::GetNextItem (vdsFolderItem * pFolderItem)"
.PP
.SS "int vdsFolder::Open (const char * folderName)"
.PP
.SS "int vdsFolder::RemoveAll ()"
.PP
.SH "Member Data Documentation"
.PP 
.SS "vdsProxyObject* \fBvdsFolder::m_pProxyObject\fP\fC [private]\fP"
.PP
Definition at line 53 of file vdsFolder.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for vdsf C++ API from the source code.
