.TH "vdsFolder" 3 "11 Oct 2007" "Version 0.1" "vdsf C++ API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vdsFolder \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 33 of file vdsFolder.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvdsFolder\fP (vdsSession &session)"
.br
.ti -1c
.RI "virtual \fB~vdsFolder\fP ()"
.br
.ti -1c
.RI "int \fBOpen\fP (const char *folderName)"
.br
.ti -1c
.RI "int \fBClose\fP ()"
.br
.ti -1c
.RI "int \fBGetFirst\fP (vdsFolderEntry *pEntry)"
.br
.ti -1c
.RI "int \fBGetNext\fP (vdsFolderEntry *pEntry)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "vdsProxyObject * \fBm_pProxyObject\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vdsFolder::vdsFolder (vdsSession & session)"
.PP
.SS "virtual vdsFolder::~vdsFolder ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "int vdsFolder::Open (const char * folderName)"
.PP
.SS "int vdsFolder::Close ()"
.PP
.SS "int vdsFolder::GetFirst (vdsFolderEntry * pEntry)"
.PP
.SS "int vdsFolder::GetNext (vdsFolderEntry * pEntry)"
.PP
.SH "Member Data Documentation"
.PP 
.SS "vdsProxyObject* \fBvdsFolder::m_pProxyObject\fP\fC [private]\fP"
.PP
Definition at line 55 of file vdsFolder.

.SH "Author"
.PP 
Generated automatically by Doxygen for vdsf C++ API from the source code.
