.TH "vdsInfo" 3 "25 Jun 2008" "Version 0.3.0" "vdsf C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vdsInfo \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vdsCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
This data structure is used to retrieve the status of the virtual data space. 
.PP
Definition at line 261 of file vdsCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBtotalSizeInBytes\fP"
.br
.RI "\fITotal size of the virtual data space. \fP"
.ti -1c
.RI "size_t \fBallocatedSizeInBytes\fP"
.br
.RI "\fITotal size of the allocated blocks. \fP"
.ti -1c
.RI "size_t \fBnumObjects\fP"
.br
.RI "\fINumber of API objects in the vds (internal objects are not counted). \fP"
.ti -1c
.RI "size_t \fBnumGroups\fP"
.br
.RI "\fITotal number of groups of blocks. \fP"
.ti -1c
.RI "size_t \fBnumMallocs\fP"
.br
.RI "\fINumber of calls to allocate groups of blocks. \fP"
.ti -1c
.RI "size_t \fBnumFrees\fP"
.br
.RI "\fINumber of calls to free groups of blocks. \fP"
.ti -1c
.RI "size_t \fBlargestFreeInBytes\fP"
.br
.RI "\fILargest contiguous group of free blocks. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t \fBvdsInfo::allocatedSizeInBytes\fP"
.PP
Total size of the allocated blocks. 
.PP
Definition at line 267 of file vdsCommon.h.
.SS "size_t \fBvdsInfo::largestFreeInBytes\fP"
.PP
Largest contiguous group of free blocks. 
.PP
Definition at line 282 of file vdsCommon.h.
.SS "size_t \fBvdsInfo::numFrees\fP"
.PP
Number of calls to free groups of blocks. 
.PP
Definition at line 279 of file vdsCommon.h.
.SS "size_t \fBvdsInfo::numGroups\fP"
.PP
Total number of groups of blocks. 
.PP
Definition at line 273 of file vdsCommon.h.
.SS "size_t \fBvdsInfo::numMallocs\fP"
.PP
Number of calls to allocate groups of blocks. 
.PP
Definition at line 276 of file vdsCommon.h.
.SS "size_t \fBvdsInfo::numObjects\fP"
.PP
Number of API objects in the vds (internal objects are not counted). 
.PP
Definition at line 270 of file vdsCommon.h.
.SS "size_t \fBvdsInfo::totalSizeInBytes\fP"
.PP
Total size of the virtual data space. 
.PP
Definition at line 264 of file vdsCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for vdsf C API from the source code.
