.TH "vdsInfo" 3 "10 Nov 2007" "Version 0.1" "vdsf C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vdsInfo \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vdsCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
Definition at line 124 of file vdsCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBtotalSizeInBytes\fP"
.br
.ti -1c
.RI "size_t \fBallocatedSizeInBytes\fP"
.br
.ti -1c
.RI "size_t \fBnumObjects\fP"
.br
.ti -1c
.RI "size_t \fBnumGroups\fP"
.br
.ti -1c
.RI "size_t \fBnumMallocs\fP"
.br
.ti -1c
.RI "size_t \fBnumFrees\fP"
.br
.ti -1c
.RI "size_t \fBlargestFreeInBytes\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t \fBvdsInfo::totalSizeInBytes\fP"
.PP
Definition at line 126 of file vdsCommon.h.
.SS "size_t \fBvdsInfo::allocatedSizeInBytes\fP"
.PP
Definition at line 128 of file vdsCommon.h.
.SS "size_t \fBvdsInfo::numObjects\fP"
.PP
Definition at line 130 of file vdsCommon.h.
.SS "size_t \fBvdsInfo::numGroups\fP"
.PP
Definition at line 132 of file vdsCommon.h.
.SS "size_t \fBvdsInfo::numMallocs\fP"
.PP
Definition at line 134 of file vdsCommon.h.
.SS "size_t \fBvdsInfo::numFrees\fP"
.PP
Definition at line 136 of file vdsCommon.h.
.SS "size_t \fBvdsInfo::largestFreeInBytes\fP"
.PP
Definition at line 138 of file vdsCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for vdsf C API from the source code.
