.TH "vdsKeyDefinition" 3 "25 Jun 2008" "Version 0.3.0" "vdsf C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vdsKeyDefinition \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vdsCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
Description of the structure of the hash map key. 
.PP
Definition at line 144 of file vdsCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBvdsKeyType\fP \fBtype\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.ti -1c
.RI "size_t \fBminLength\fP"
.br
.ti -1c
.RI "size_t \fBmaxLength\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "enum \fBvdsKeyType\fP \fBvdsKeyDefinition::type\fP"
.PP
Definition at line 146 of file vdsCommon.h.
.SS "size_t \fBvdsKeyDefinition::length\fP"
.PP
Definition at line 147 of file vdsCommon.h.
.SS "size_t \fBvdsKeyDefinition::minLength\fP"
.PP
Definition at line 148 of file vdsCommon.h.
.SS "size_t \fBvdsKeyDefinition::maxLength\fP"
.PP
Definition at line 149 of file vdsCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for vdsf C API from the source code.
