.TH "psoObjectDefinition" 3 "18 Aug 2008" "Version 0.3.0" "vdsf C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psoObjectDefinition \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vdsCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
This struct has a variable length. 
.PP
Definition at line 180 of file vdsCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBpsoObjectType\fP \fBtype\fP"
.br
.ti -1c
.RI "unsigned int \fBnumFields\fP"
.br
.ti -1c
.RI "\fBpsoKeyDefinition\fP \fBkey\fP"
.br
.RI "\fIThe data definition of the key (hash map only). \fP"
.ti -1c
.RI "\fBvdsFieldDefinition\fP \fBfields\fP [1]"
.br
.RI "\fIThe data definition of the fields. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "enum \fBpsoObjectType\fP \fBpsoObjectDefinition::type\fP"
.PP
Definition at line 182 of file vdsCommon.h.
.SS "unsigned int \fBpsoObjectDefinition::numFields\fP"
.PP
Definition at line 184 of file vdsCommon.h.
.SS "\fBpsoKeyDefinition\fP \fBpsoObjectDefinition::key\fP"
.PP
The data definition of the key (hash map only). 
.PP
Definition at line 187 of file vdsCommon.h.
.SS "\fBvdsFieldDefinition\fP \fBpsoObjectDefinition::fields\fP[1]"
.PP
The data definition of the fields. 
.PP
Definition at line 190 of file vdsCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for vdsf C API from the source code.
