.TH "vdsObjStatus" 3 "3 Nov 2007" "Version 0.1" "vdsf C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vdsObjStatus \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vdsCommon.h>\fP
.PP
.SH "Detailed Description"
.PP 
Definition at line 108 of file vdsCommon.h.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBvdsObjectType\fP \fBtype\fP"
.br
.ti -1c
.RI "size_t \fBnumBlocks\fP"
.br
.ti -1c
.RI "size_t \fBnumBlockGroup\fP"
.br
.ti -1c
.RI "size_t \fBnumDataItem\fP"
.br
.ti -1c
.RI "size_t \fBfreeBytes\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBvdsObjectType\fP \fBvdsObjStatus::type\fP"
.PP
Definition at line 110 of file vdsCommon.h.
.SS "size_t \fBvdsObjStatus::numBlocks\fP"
.PP
Definition at line 112 of file vdsCommon.h.
.SS "size_t \fBvdsObjStatus::numBlockGroup\fP"
.PP
Definition at line 114 of file vdsCommon.h.
.SS "size_t \fBvdsObjStatus::numDataItem\fP"
.PP
Definition at line 116 of file vdsCommon.h.
.SS "size_t \fBvdsObjStatus::freeBytes\fP"
.PP
Definition at line 118 of file vdsCommon.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for vdsf C API from the source code.
