.TH "vdsProcess" 3 "4 Nov 2006" "Version 0.1" "vdsf C++ API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vdsProcess \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vdsProcess.h>\fP
.PP
.SH "Detailed Description"
.PP 
Definition at line 34 of file vdsProcess.h.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvdsProcess\fP ()"
.br
.ti -1c
.RI "virtual \fB~vdsProcess\fP ()"
.br
.ti -1c
.RI "int \fBInitialize\fP (const char *wdAddress, bool protectionNeeded=false)"
.br
.ti -1c
.RI "void \fBTerminate\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "vdsProcessHook * \fBm_pProcessHook\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vdsProcess::vdsProcess ()"
.PP
.SS "virtual vdsProcess::~vdsProcess ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "int vdsProcess::Initialize (const char * wdAddress, bool protectionNeeded = \fCfalse\fP)"
.PP
.SS "void vdsProcess::Terminate ()"
.PP
.SH "Member Data Documentation"
.PP 
.SS "vdsProcessHook* \fBvdsProcess::m_pProcessHook\fP\fC [private]\fP"
.PP
Definition at line 49 of file vdsProcess.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for vdsf C++ API from the source code.
