.TH "vdsQueue" 3 "4 Nov 2006" "Version 0.1" "vdsf C++ API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vdsQueue \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vdsQueue.h>\fP
.PP
.SH "Detailed Description"
.PP 
Definition at line 36 of file vdsQueue.h.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvdsQueue\fP (vdsSession &session)"
.br
.ti -1c
.RI "virtual \fB~vdsQueue\fP ()"
.br
.ti -1c
.RI "int \fBOpen\fP (const char *queueName)"
.br
.ti -1c
.RI "int \fBClose\fP ()"
.br
.ti -1c
.RI "int \fBInsertItem\fP (const void *pItem, size_t length)"
.br
.ti -1c
.RI "int \fBRemoveItem\fP (vdsQueueItem *pQueueItem)"
.br
.ti -1c
.RI "int \fBRemoveItem\fP (vdsQueueItem &queueItem)"
.br
.ti -1c
.RI "int \fBRemoveItem\fP (void *pItem, size_t length)"
.br
.ti -1c
.RI "int \fBGetItem\fP (vdsIteratorType flag, void *pItem, size_t length)"
.br
.RI "\fIGetItem does not remove the items from the queue. \fP"
.ti -1c
.RI "int \fBStatus\fP (size_t *pNumValidItems, size_t *pNumTotalItems)"
.br
.RI "\fIA struct might be better here. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "vdsProxyObject * \fBm_pProxyObject\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vdsQueue::vdsQueue (vdsSession & session)"
.PP
.SS "virtual vdsQueue::~vdsQueue ()\fC [virtual]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "int vdsQueue::Close ()"
.PP
.SS "int vdsQueue::GetItem (vdsIteratorType flag, void * pItem, size_t length)"
.PP
GetItem does not remove the items from the queue. 
.PP
.SS "int vdsQueue::InsertItem (const void * pItem, size_t length)"
.PP
.SS "int vdsQueue::Open (const char * queueName)"
.PP
.SS "int vdsQueue::RemoveItem (void * pItem, size_t length)"
.PP
.SS "int vdsQueue::RemoveItem (vdsQueueItem & queueItem)"
.PP
.SS "int vdsQueue::RemoveItem (vdsQueueItem * pQueueItem)"
.PP
.SS "int vdsQueue::Status (size_t * pNumValidItems, size_t * pNumTotalItems)"
.PP
A struct might be better here. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "vdsProxyObject* \fBvdsQueue::m_pProxyObject\fP\fC [private]\fP"
.PP
Definition at line 65 of file vdsQueue.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for vdsf C++ API from the source code.
