# Copyright (C) 2007-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

all: 

check_PROGRAMS =                            \
        $(DIR_RELEASE)\DeleteNullContext.exe     \
        $(DIR_RELEASE)\DeleteNullHash.exe        \
        $(DIR_RELEASE)\DeleteNullItem.exe        \
        $(DIR_RELEASE)\DeletePass.exe            \
        $(DIR_RELEASE)\FiniNullHash.exe          \
        $(DIR_RELEASE)\FiniPass.exe              \
        $(DIR_RELEASE)\GetFirstNullHash.exe      \
        $(DIR_RELEASE)\GetFirstNullOffset.exe    \
        $(DIR_RELEASE)\GetFirstPass.exe          \
        $(DIR_RELEASE)\GetNextNullHash.exe       \
        $(DIR_RELEASE)\GetNextNullNextOffset.exe \
        $(DIR_RELEASE)\GetNextNullPrevOffset.exe \
        $(DIR_RELEASE)\GetNextPass.exe           \
        $(DIR_RELEASE)\GetNullBucket.exe         \
        $(DIR_RELEASE)\GetNullContext.exe        \
        $(DIR_RELEASE)\GetNullHash.exe           \
        $(DIR_RELEASE)\GetNullItem.exe           \
        $(DIR_RELEASE)\GetNullKey.exe            \
        $(DIR_RELEASE)\GetPass.exe               \
        $(DIR_RELEASE)\GetZeroKeyLength.exe      \
        $(DIR_RELEASE)\InitNullContext.exe       \
        $(DIR_RELEASE)\InitNullHash.exe          \
        $(DIR_RELEASE)\InitNullOffset.exe        \
        $(DIR_RELEASE)\InitPass.exe              \
        $(DIR_RELEASE)\InsertNullContext.exe     \
        $(DIR_RELEASE)\InsertNullData.exe        \
        $(DIR_RELEASE)\InsertNullHash.exe        \
        $(DIR_RELEASE)\InsertNullKey.exe         \
        $(DIR_RELEASE)\InsertNullNewItem.exe     \
        $(DIR_RELEASE)\InsertPass.exe            \
        $(DIR_RELEASE)\InsertZeroDataLength.exe  \
        $(DIR_RELEASE)\InsertZeroKeyLength.exe   \
        $(DIR_RELEASE)\ResizeNullContext.exe     \
        $(DIR_RELEASE)\ResizeNullHash.exe        \
        $(DIR_RELEASE)\ResizePass.exe            

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q $(CLEANFILES)

