# Copyright (C) 2006-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

DLL_RELEASE = ..\..\..\Release2005
DLL_DEBUG = ..\..\..\Debug2005

all: 

CLEANFILES = *~ 

check_PROGRAMS =                             \
        $(DIR_RELEASE)\CloseInvalidSig.exe   \
        $(DIR_RELEASE)\CloseNullDir.exe      \
        $(DIR_RELEASE)\ClosePass.exe         \
        $(DIR_RELEASE)\FiniInvalidSig.exe    \
        $(DIR_RELEASE)\FiniNullDir.exe       \
        $(DIR_RELEASE)\FiniPass.exe          \
        $(DIR_RELEASE)\GetNextInvalidSig.exe \
        $(DIR_RELEASE)\GetNextNoOpen.exe     \
        $(DIR_RELEASE)\GetNextNoSuchDir.exe  \
        $(DIR_RELEASE)\GetNextNullDir.exe    \
        $(DIR_RELEASE)\GetNextNullError.exe  \
        $(DIR_RELEASE)\GetNextNullpDir.exe   \
        $(DIR_RELEASE)\GetNextPass.exe       \
        $(DIR_RELEASE)\InitNullDir.exe       \
        $(DIR_RELEASE)\InitPass.exe          \
        $(DIR_RELEASE)\OpenCallTwice.exe     \
        $(DIR_RELEASE)\OpenInvalidSig.exe    \
        $(DIR_RELEASE)\OpenNoInit.exe        \
        $(DIR_RELEASE)\OpenNoSuchDir.exe     \
        $(DIR_RELEASE)\OpenNullDir.exe       \
        $(DIR_RELEASE)\OpenNullDirname.exe   \
        $(DIR_RELEASE)\OpenNullError.exe     \
        $(DIR_RELEASE)\OpenPass.exe          \
        $(DIR_RELEASE)\Tests.exe             

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)\Tests
	-@rmdir /Q $(DIR_DEBUG)\Tests
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)\Tests
	-@rmdir /Q $(DIR_RELEASE)\Tests
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q ProjectFiles\*.dep
	-@erase /Q ProjectFiles\*.plg
	-@erase /Q ProjectFiles\*.mak
	-@erase /Q $(CLEANFILES)

