# Copyright (C) 2006-2007 Daniel Prevost <dprevost@users.sourceforge.net>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

include ..\Makefile.inc.Win32

all: 

CLEANFILES = *~ 

check_PROGRAMS =                                 \
                 .\Release\CloseInvalidSig.exe   \
                 .\Release\CloseNullDir.exe      \
                 .\Release\ClosePass.exe         \
                 .\Release\FiniInvalidSig.exe    \
                 .\Release\FiniNullDir.exe       \
                 .\Release\FiniPass.exe          \
                 .\Release\GetNextInvalidSig.exe \
                 .\Release\GetNextNoOpen.exe     \
                 .\Release\GetNextNoSuchDir.exe  \
                 .\Release\GetNextNullDir.exe    \
                 .\Release\GetNextNullError.exe  \
                 .\Release\GetNextNullpDir.exe   \
                 .\Release\GetNextPass.exe       \
                 .\Release\InitNullDir.exe       \
                 .\Release\InitPass.exe          \
                 .\Release\OpenCallTwice.exe     \
                 .\Release\OpenInvalidSig.exe    \
                 .\Release\OpenNoInit.exe        \
                 .\Release\OpenNoSuchDir.exe     \
                 .\Release\OpenNullDir.exe       \
                 .\Release\OpenNullDirname.exe   \
                 .\Release\OpenNullError.exe     \
                 .\Release\OpenPass.exe          \
                 .\Release\Tests.exe             

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release\=.\Debug\)
#

check: $(OUTDIR) $(check_PROGRAMS)
	cscript RunTests.vbs --path=Release $(VBS_VERBOSE)

checkdebug: $(OUTDIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=Debug $(VBS_VERBOSE)

clean: 
	-@erase /Q Debug\Tests
	-@rmdir /Q Debug\Tests
	-@erase /Q Debug
	-@rmdir /Q Debug
	-@erase /Q Release\Tests
	-@rmdir /Q Release\Tests
	-@erase /Q Release
	-@rmdir /Q Release
	-@erase /Q ProjectFiles\*.dep
	-@erase /Q ProjectFiles\*.plg
	-@erase /Q ProjectFiles\*.mak
	-@erase /Q $(CLEANFILES)

