#! /usr/bin/env python
# encoding: utf-8
# :mode=python:  - For jedit

# Copyright (C) 2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

test_list = [
   'CloseInvalidSig',
   'CloseNullDir',
   'ClosePass',
   'FiniInvalidSig',
   'FiniNullDir',
   'FiniPass',
   'GetNextInvalidSig',
   'GetNextNoOpen',
   'GetNextNoSuchDir',
   'GetNextNullDir',
   'GetNextNullError',
   'GetNextNullpDir',
   'GetNextPass',
   'InitNullDir',
   'InitPass',
   'OpenCallTwice',
   'OpenInvalidSig',
   'OpenNoInit',
   'OpenNoSuchDir',
   'OpenNullDir',
   'OpenNullDirname',
   'OpenNullError',
   'OpenPass',
   'Tests']


def build(bld):
   print ' building in Tests/DirAccess'
   for prog in test_list:
      prog_c = prog + '.c'
      obj = bld.new_task_gen(
         features     = 'cc cprogram',
         source       = prog_c,
         target       = prog,
         includes     = '../../..',
         install_path = None,
         uselib_local = 'Common') 
      obj.unit_test = 1

def check(ctx):
#   ctx.recurse('Tests')
   print 'ok check DirAccess'
   print dir(ctx)

