# Copyright (C) 2008-2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# To use this makefile with VS 2008, you must change the macros defined here
# AND the macro check_PROGRAMS_DEBUG near the end of this file

include ..\Makefile.inc.Win32.2005

RELEASE = Release2005
DEBUG = Debug2005
DLL_RELEASE = ..\..\..\Release2005
DLL_DEBUG = ..\..\..\Debug2005

all: 

check_PROGRAMS =                             \
        $(DIR_RELEASE)\Close.exe             \
        $(DIR_RELEASE)\Create.exe            \
        $(DIR_RELEASE)\Definition.exe        \
        $(DIR_RELEASE)\FirstNullData.exe     \
        $(DIR_RELEASE)\FirstNullHandle.exe   \
        $(DIR_RELEASE)\FirstNullLength.exe   \
        $(DIR_RELEASE)\FirstPass.exe         \
        $(DIR_RELEASE)\FirstWrongHandle.exe  \
        $(DIR_RELEASE)\GetFirst.exe          \
        $(DIR_RELEASE)\GetNext.exe           \
        $(DIR_RELEASE)\NextNoFirst.exe       \
        $(DIR_RELEASE)\NextNullData.exe      \
        $(DIR_RELEASE)\NextNullHandle.exe    \
        $(DIR_RELEASE)\NextNullLength.exe    \
        $(DIR_RELEASE)\NextPass.exe          \
        $(DIR_RELEASE)\NextWrongHandle.exe   \
        $(DIR_RELEASE)\OpenNoSession.exe     \
        $(DIR_RELEASE)\OpenPass.exe          \
        $(DIR_RELEASE)\Pop.exe               \
        $(DIR_RELEASE)\Push.exe              \
        $(DIR_RELEASE)\RecordDef.exe         \
        $(DIR_RELEASE)\RemoveNullData.exe    \
        $(DIR_RELEASE)\RemoveNullHandle.exe  \
        $(DIR_RELEASE)\RemoveNullLength.exe  \
        $(DIR_RELEASE)\RemovePass.exe        \
        $(DIR_RELEASE)\RemoveWrongHandle.exe \
        $(DIR_RELEASE)\Status.exe            

check_PROGRAMS_DEBUG = $(check_PROGRAMS:.\Release2005\=.\Debug2005\)

check: $(DIR_RELEASE) $(check_PROGRAMS)
	cscript RunTests.vbs --path=$(DIR_RELEASE) --dllpath=$(DLL_RELEASE) $(VBS_VERBOSE)

checkdebug: $(DIR_DEBUG) $(check_PROGRAMS_DEBUG) 
	cscript RunTests.vbs --path=$(DIR_DEBUG) --dllpath=$(DLL_DEBUG) $(VBS_VERBOSE)

clean: 
	-@erase /Q $(DIR_DEBUG)
	-@rmdir /Q $(DIR_DEBUG)
	-@erase /Q $(DIR_RELEASE)
	-@rmdir /Q $(DIR_RELEASE)
	-@erase /Q $(CLEANFILES)

