.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH vdswd 1 "9 April 2008" VDSF "User Commands"
.SH NAME
vdswd \- starts the vdsf watchdog
.SH SYNOPSIS
.SS "TESTING THE CONFIGURATION FILE (AND EXIT):"
\*(T<\fBvdswd \-c|\-\-config\fR\*(T> \fIconfig_filename \fR\*(T<\fB\-t|\-\-test\fR\*(T>
.SS "VERIFYING THE VDS (AND EXIT):"
\*(T<\fBvdswd \-c|\-\-config\fR\*(T> \fIconfig_filename \fR\*(T<\fB\-v|\-\-verify\fR\*(T>
.SS "GETTING (MINIMAL) HELP:"
\*(T<\fBvdswd \-h|\-\-help|\-?\fR\*(T>
.SS "RUNNING NORMALLY:"
\*(T<\fBvdswd \-c|\-\-config\fR\*(T> \fIconfig_filename \fR[\*(T<\fB\-d|\-\-daemon\fR\*(T>]
.SH DESCRIPTION
vdswd is the crash-recovery daemon (the watchdog) of the Virtual Data Space
Framework (VDSF). Currently, crash recovery is only done when this program is 
started.
.SH OPTIONS
.TP 
\*(T<\fB\-c\fR\*(T>, \*(T<\fB\-\-config\fR\*(T> \fIconfig_filename\fR
The name of the configuration file (see 
CONFIGURATION [\fBvdswd\fR(1)]
below).
.TP 
\*(T<\fB\-d\fR\*(T>, \*(T<\fB\-\-daemon\fR\*(T>
Become a Unix daemon. Error reporting is done using the system logger (syslog).
This option is not available on Windows.
.TP 
\*(T<\fB\-h\fR\*(T>, \*(T<\fB\-\-help\fR\*(T>, \*(T<\fB\-?\fR\*(T>
Display minimal usage information.
.TP 
\*(T<\fB\-t\fR\*(T>, \*(T<\fB\-\-test\fR\*(T>
Test the configuration file and exit.
.TP 
\*(T<\fB\-v\fR\*(T>, \*(T<\fB\-\-verify\fR\*(T>
Verify the content of the shared-memory file (VDS) without modifying it 
and exit.
.SH CONFIGURATION
The syntax of the configuration file is very simple, pairs of keys and values.
Lines starting with # are comments.
.TP 
\fIVDSLocation\fR
The path of the directory where the watchdog will find the shared-memory file
and auxiliary files (these files will be created if they do not exist).
.TP 
\fIMemorySize\fR
The total size of the shared memory in units of kiloBytes.
.TP 
\fIWatchdogAddress\fR
The local TCP/IP port the watchdog will use to listen for new connection 
requests.
.TP 
\fIFilePermissions\fR
The file permissions used for the shared-memory file.
.TP 
\fIDirectoryPermissions\fR
The file permissions used for the directory holding the shared-memory file.
.SH "REPORTING BUGS"
Report bugs to <dprevost@users.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2008 Daniel Pr\('evost.
