/*
 * This file was generated by the program errorParser
 * using the input file wdErrors.xml.
 * Date: Wed May 28 22:30:59 2008.
 *
 * The version of this interface is 0.3.
 *
 * Copyright (C) 2006-2008 Daniel Prevost
 *
 * This file is part of the vdsf library (Virtual Data Space Framework).
 *
 * This file may be distributed and/or modified under the terms of the
 * GNU General Public License version 2 as published by the Free
 * Software Foundation and appearing in the file COPYING included in
 * the packaging of this library.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 */

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#include <stdlib.h> /* Any system file will do. Needed for NULL. */
#include "wdErrorHandler.h"

struct vdsw_MsgStruct
{
    int  errorNumber;
    const char * message;
};

typedef struct vdsw_MsgStruct vdsw_MsgStruct;

/* VDSW_OK */
vdsw_MsgStruct vdsw_Msg0 = {
    0, "No error..." };

/* VDSW_XML_CONFIG_NOT_OPEN */
vdsw_MsgStruct vdsw_Msg1 = {
    100, "Error opening the XML config file." };

/* VDSW_XML_READ_ERROR */
vdsw_MsgStruct vdsw_Msg2 = {
    101, "Error reading the XML config file." };

/* VDSW_XML_NO_ROOT */
vdsw_MsgStruct vdsw_Msg3 = {
    102, "No root element in the XML document." };

/* VDSW_XML_INVALID_ROOT */
vdsw_MsgStruct vdsw_Msg4 = {
    103, "The root element is not the expected root." };

/* VDSW_XML_NO_SCHEMA_LOCATION */
vdsw_MsgStruct vdsw_Msg5 = {
    104, "The attribute xsi:schemaLocation was not found." };

/* VDSW_XML_MALFORMED_SCHEMA_LOCATION */
vdsw_MsgStruct vdsw_Msg6 = {
    105, "The attribute xsi:schemaLocation is not well formed." };

/* VDSW_XML_PARSER_CONTEXT_FAILED */
vdsw_MsgStruct vdsw_Msg7 = {
    106, "The creation of a new schema parser context failed." };

/* VDSW_XML_PARSE_SCHEMA_FAILED */
vdsw_MsgStruct vdsw_Msg8 = {
    107, "Failure when parsing the XML schema for config." };

/* VDSW_XML_VALID_CONTEXT_FAILED */
vdsw_MsgStruct vdsw_Msg9 = {
    108, "The creation of a new XML Schemas validation context failed." };

/* VDSW_XML_VALIDATION_FAILED */
vdsw_MsgStruct vdsw_Msg10 = {
    109, "Document validation for the config file failed." };

/* VDSW_CFG_VDS_LOCATION_TOO_LONG */
vdsw_MsgStruct vdsw_Msg11 = {
    110, "Config: vds_location is too long." };

/* VDSW_CFG_VDS_LOCATION_IS_MISSING */
vdsw_MsgStruct vdsw_Msg12 = {
    111, "Config: vds_location is missing." };

/* VDSW_CFG_MEM_SIZE_IS_MISSING */
vdsw_MsgStruct vdsw_Msg13 = {
    112, "Config: mem_size is missing." };

/* VDSW_CFG_SIZE_IS_MISSING */
vdsw_MsgStruct vdsw_Msg14 = {
    113, "Config: mem_size:size is missing." };

/* VDSW_CFG_UNITS_IS_MISSING */
vdsw_MsgStruct vdsw_Msg15 = {
    114, "Config: mem_size:units is missing." };

/* VDSW_CFG_WATCHDOG_ADDRESS_IS_MISSING */
vdsw_MsgStruct vdsw_Msg16 = {
    115, "Config: watchdog_address is missing." };

/* VDSW_CFG_FILE_ACCESS_IS_MISSING */
vdsw_MsgStruct vdsw_Msg17 = {
    116, "Config: file_access is missing." };

/* VDSW_CFG_ACCESS_IS_MISSING */
vdsw_MsgStruct vdsw_Msg18 = {
    117, "Config: file_access:access is missing." };

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

/* Array of pointers to previous structs */
vdsw_MsgStruct * vdsw_MsgArray[19] = {
    &vdsw_Msg0,
    &vdsw_Msg1,
    &vdsw_Msg2,
    &vdsw_Msg3,
    &vdsw_Msg4,
    &vdsw_Msg5,
    &vdsw_Msg6,
    &vdsw_Msg7,
    &vdsw_Msg8,
    &vdsw_Msg9,
    &vdsw_Msg10,
    &vdsw_Msg11,
    &vdsw_Msg12,
    &vdsw_Msg13,
    &vdsw_Msg14,
    &vdsw_Msg15,
    &vdsw_Msg16,
    &vdsw_Msg17,
    &vdsw_Msg18
};

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

const char * vdsw_ErrorMessage( int errnum )
{
    int i;

    for ( i = 0; i < 19; ++i ) {
        if ( errnum == vdsw_MsgArray[i]->errorNumber ) {
            return vdsw_MsgArray[i]->message;
        }
    }

    return NULL;
}

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

